#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["model2vec>=0.9", "numpy"]
# ///
"""browse claude code conversations in a browser.

reads ~/.claude/projects/*/*.jsonl, builds a cached index, serves a local UI.
titles come from a user-set `custom-title`, else an `ai-title` record (what
/resume shows), else a `summary` record, else a cleaned first user prompt.
subagent transcripts under <project>/<session-id>/subagents/ are indexed too,
so search reaches delegated work and reports it against its parent session.

usage:
    ./ccbrowse.py              # index (incremental) and serve on :4173
    ./ccbrowse.py --port 8080
    ./ccbrowse.py --reindex    # throw away the cache first
    ./ccbrowse.py search foo --json
    ./ccbrowse.py list --limit 5
    ./ccbrowse.py show <session-id>
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sqlite3
import sys
import threading
import webbrowser
from concurrent.futures import ProcessPoolExecutor
from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

PROJECTS = Path.home() / ".claude" / "projects"
CACHE_DB = Path.home() / ".cache" / "cc-browse" / "index.db"
VEC_FILE = CACHE_DB.parent / "vectors.npy"
UI_FILE = Path(__file__).parent / "ui.html"

SCHEMA_VERSION = 6

# how often the background thread re-runs the incremental index
REFRESH_SECS = 60

# static embeddings: a token-lookup distillation, no transformer forward pass.
# ~0.03 ms/message, which is what makes indexing the whole corpus practical.
EMBED_MODEL = "minishlab/potion-base-8M"
try:
    import numpy as np
    from model2vec import StaticModel

    SEMANTIC_OK = True
except ImportError:  # optional; the ui hides the mode when it is missing
    SEMANTIC_OK = False

# how many trailing messages to keep in the index for the list preview
TAIL_KEEP = 6
TAIL_CHARS = 400
# per-message cap for the searchable text index
FTS_CHARS = 4000

# noise wrappers that make a first prompt unreadable as a title
_STRIP_BLOCKS = re.compile(
    r"<(system-reminder|local-command-stdout|command-args|command-contents)>.*?</\1>",
    re.S,
)
_CMD_NAME = re.compile(r"<command-name>\s*(.*?)\s*</command-name>", re.S)
_CMD_MSG = re.compile(r"</?command-message>", re.S)
_ANY_TAG = re.compile(r"<[^>]{1,60}>")
# a wrapper with attributes blows past the 60-char cap above — subagent prompts
# arrive inside one of these, so the tag would otherwise become the title
_ATTR_TAG = re.compile(r"</?[a-zA-Z][\w-]*(?:\s+[\w-]+=\"[^\"]*\")*\s*/?>")
# claude code prepends this to messages produced by local command output
_CAVEAT = re.compile(
    r"Caveat: The messages below were generated by the user while running local"
    r" commands\. DO NOT.*?(?=$|\n)",
    re.S,
)


def clean_prompt(text: str) -> str:
    """turn a raw first user message into something readable as a title."""
    if not text:
        return ""
    text = _CAVEAT.sub(" ", text)
    cmd = _CMD_NAME.search(text)
    body = _STRIP_BLOCKS.sub(" ", text)
    body = _CMD_MSG.sub(" ", body)
    body = _ATTR_TAG.sub(" ", body)
    body = _ANY_TAG.sub(" ", body)
    body = re.sub(r"\s+", " ", body).strip()
    if cmd:
        name = cmd.group(1)
        # a slash command with no extra prose is more useful shown as the command
        return f"{name} {body}".strip() if body and body != name else name
    return body


def block_text(block: dict) -> tuple[str, str]:
    """(kind, text) for one assistant/user content block."""
    kind = block.get("type")
    if kind == "text":
        return "text", block.get("text", "")
    if kind == "thinking":
        return "thinking", block.get("thinking", "")
    if kind == "tool_use":
        name = block.get("name", "tool")
        inp = block.get("input", {})
        if isinstance(inp, dict):
            hint = (
                inp.get("command")
                or inp.get("file_path")
                or inp.get("pattern")
                or inp.get("prompt")
                or inp.get("description")
                or ""
            )
        else:
            hint = str(inp)
        return "tool", f"{name}: {str(hint)[:200]}"
    if kind == "tool_result":
        content = block.get("content", "")
        if isinstance(content, list):
            content = " ".join(
                c.get("text", "") for c in content if isinstance(c, dict)
            )
        return "tool_result", str(content)
    if kind == "image":
        return "image", "[image]"
    return kind or "unknown", ""


def message_blocks(msg: dict) -> list[tuple[str, str, dict]]:
    """(kind, text, raw block) for every content block of a message."""
    content = msg.get("content")
    if isinstance(content, str):
        return [("text", content, {})]
    if isinstance(content, list):
        return [(*block_text(b), b) for b in content if isinstance(b, dict)]
    return []


def message_parts(msg: dict) -> list[tuple[str, str]]:
    return [(k, t) for k, t, _ in message_blocks(msg)]


def file_identity(path: Path) -> tuple[str, str, str, str]:
    """(kind, session_id, parent_id, agent_id) implied by a log's location.

    top-level logs are `<project>/<uuid>.jsonl`; anything deeper is a subagent
    transcript living under `<project>/<owning-uuid>/subagents/...`. subagent
    files carry the *owning session's* id in their own `sessionId` field, so the
    row id has to come from the path or every subagent would collide with it.

    `rel[1]` is the owning session at any nesting depth: a subagent that spawns
    its own subagents does not get a directory of its own — everything it
    spawns is written flat into the same session-level `subagents/` tree — so
    this resolves to the top-level session rather than to an intermediate
    agent. (`parent_agent_id` from the sidecar records the immediate spawner.)
    """
    try:
        rel = path.relative_to(PROJECTS).parts
    except ValueError:
        return "session", path.stem, "", ""
    if len(rel) <= 2:
        return "session", path.stem, "", ""
    parent = rel[1]
    tail = "~".join(rel[2:])[: -len(".jsonl")] if path.suffix == ".jsonl" else "~".join(rel[2:])
    agent = path.stem[len("agent-"):] if path.stem.startswith("agent-") else path.stem
    return "subagent", f"{parent}~{tail}", parent, agent


def read_sidecar(path: Path) -> dict:
    """`<transcript>.meta.json` — what the harness knew when it spawned the agent.

    two thirds of transcripts have one. `description` is a human-written
    one-liner, so it beats anything inferable from the first message, and
    `toolUseId` is the spawning Task call stated outright rather than
    reconstructed from the parent log.
    """
    side = path.with_name(path.stem + ".meta.json")
    try:
        d = json.loads(side.read_text(encoding="utf-8", errors="replace"))
    except (OSError, json.JSONDecodeError):
        return {}
    return d if isinstance(d, dict) else {}


def scan_file(path_str: str) -> dict | None:
    """single pass over one session file, extracting index metadata + search text."""
    path = Path(path_str)
    try:
        st = path.stat()
    except OSError:
        return None

    kind_of_file, session_id, parent_id, agent_id = file_identity(path)
    side = read_sidecar(path) if kind_of_file == "subagent" else {}
    rec = {
        "path": path_str,
        "mtime": int(st.st_mtime),
        "size": st.st_size,
        "session_id": session_id,
        "kind": kind_of_file,
        "parent_id": parent_id,
        "agent_id": agent_id,
        "agent_type": str(side.get("customAgentType") or side.get("agentType") or ""),
        "agent_name": str(side.get("name") or ""),
        "description": str(side.get("description") or ""),
        "model": str(side.get("model") or ""),
        "spawn_depth": int(side.get("spawnDepth") or 0),
        "parent_agent_id": str(side.get("parentAgentId") or ""),
        "tool_use_id": str(side.get("toolUseId") or ""),
        "project": "",
        "branch": "",
        "custom_title": "",
        "ai_title": "",
        "summary": "",
        "first_prompt": "",
        "created": "",
        "modified": "",
        "n_user": 0,
        "n_assistant": 0,
        "n_tool": 0,
        "sidechain": 0,
    }
    tail: list[dict] = []
    docs: list[tuple[str, int, str]] = []  # (role, seq, text)
    seq = 0

    try:
        fh = path.open("r", encoding="utf-8", errors="replace")
    except OSError:
        return None

    with fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                d = json.loads(line)
            except json.JSONDecodeError:
                continue
            kind = d.get("type")

            if kind == "custom-title":
                # the user can rename a session repeatedly; the last one wins
                rec["custom_title"] = d.get("customTitle", "") or rec["custom_title"]
                continue
            if kind == "ai-title":
                rec["ai_title"] = d.get("aiTitle", "") or rec["ai_title"]
                continue
            if kind == "summary":
                rec["summary"] = d.get("summary", "") or rec["summary"]
                continue
            if kind not in ("user", "assistant"):
                continue

            if not rec["project"]:
                rec["project"] = d.get("cwd", "") or ""
            if not rec["branch"]:
                rec["branch"] = d.get("gitBranch", "") or ""
            if d.get("isSidechain"):
                rec["sidechain"] = 1
            ts = d.get("timestamp", "")
            if ts:
                if not rec["created"]:
                    rec["created"] = ts
                rec["modified"] = ts

            msg = d.get("message")
            if not isinstance(msg, dict):
                continue

            parts = message_parts(msg)
            rec["n_tool"] += sum(1 for k, _ in parts if k == "tool")
            text = " ".join(t for k, t in parts if k == "text" and t).strip()

            if kind == "user":
                rec["n_user"] += 1
                # tool results are echoed as user turns; they are not prompts
                is_tool_echo = bool(parts) and all(
                    k in ("tool_result", "image") for k, _ in parts
                )
                if not is_tool_echo and text and not rec["first_prompt"]:
                    rec["first_prompt"] = clean_prompt(text)[:300]
                if is_tool_echo:
                    continue
                text = clean_prompt(text)
            else:
                rec["n_assistant"] += 1

            if text:
                seq += 1
                docs.append((kind, seq, text[:FTS_CHARS]))
                tail.append({"role": kind, "text": text[:TAIL_CHARS]})
                if len(tail) > TAIL_KEEP:
                    tail.pop(0)

    if not rec["project"]:
        # fall back to the encoded directory name when no message carried a cwd
        try:
            encoded = path.relative_to(PROJECTS).parts[0]
        except ValueError:
            encoded = path.parent.name
        rec["project"] = "/" + encoded.lstrip("-").replace("-", "/")
    rec["tail"] = json.dumps(tail)
    # a title the user typed outranks anything generated; for a subagent the
    # sidecar's description is the closest thing to one
    rec["title"] = (
        rec["custom_title"]
        or rec["description"]
        or rec["agent_name"]
        or rec["ai_title"]
        or rec["summary"]
        or rec["first_prompt"]
        or "(empty)"
    )
    rec["day"] = (rec["modified"] or "")[:10]
    rec["_docs"] = docs
    return rec


SCHEMA = """
CREATE TABLE IF NOT EXISTS meta (k TEXT PRIMARY KEY, v TEXT);
CREATE TABLE IF NOT EXISTS sessions (
    path TEXT PRIMARY KEY,
    mtime INTEGER, size INTEGER,
    session_id TEXT, kind TEXT, parent_id TEXT, agent_id TEXT,
    agent_type TEXT, agent_name TEXT, description TEXT, model TEXT,
    spawn_depth INTEGER, parent_agent_id TEXT, tool_use_id TEXT,
    project TEXT, branch TEXT,
    custom_title TEXT, ai_title TEXT, summary TEXT, first_prompt TEXT, title TEXT,
    created TEXT, modified TEXT, day TEXT,
    n_user INTEGER, n_assistant INTEGER, n_tool INTEGER, sidechain INTEGER,
    tail TEXT
);
CREATE INDEX IF NOT EXISTS idx_modified ON sessions(modified DESC);
CREATE INDEX IF NOT EXISTS idx_project ON sessions(project);
CREATE INDEX IF NOT EXISTS idx_sid ON sessions(session_id);
CREATE INDEX IF NOT EXISTS idx_parent ON sessions(parent_id);
CREATE VIRTUAL TABLE IF NOT EXISTS msg_fts USING fts5(
    text, session_id UNINDEXED, role UNINDEXED, seq UNINDEXED,
    tokenize = 'unicode61 remove_diacritics 2'
);
"""

COLUMNS = [
    "path", "mtime", "size", "session_id", "kind", "parent_id", "agent_id",
    "agent_type", "agent_name", "description", "model", "spawn_depth",
    "parent_agent_id", "tool_use_id",
    "project", "branch",
    "custom_title", "ai_title", "summary", "first_prompt", "title",
    "created", "modified", "day",
    "n_user", "n_assistant", "n_tool", "sidechain", "tail",
]


def _remove_db() -> None:
    """drop the cache *and its wal sidecars* — a stale wal fails the next open."""
    for suffix in ("", "-wal", "-shm"):
        Path(str(CACHE_DB) + suffix).unlink(missing_ok=True)


def _open(path: Path) -> sqlite3.Connection:
    con = sqlite3.connect(path, check_same_thread=False)
    con.row_factory = sqlite3.Row
    con.execute("PRAGMA journal_mode=WAL")
    con.execute("PRAGMA synchronous=NORMAL")
    con.execute("PRAGMA busy_timeout=15000")
    con.executescript(SCHEMA)
    return con


def connect(reset: bool = False) -> sqlite3.Connection:
    CACHE_DB.parent.mkdir(parents=True, exist_ok=True)
    if reset:
        _remove_db()
    try:
        con = _open(CACHE_DB)
        row = con.execute("SELECT v FROM meta WHERE k = 'schema'").fetchone()
        ok = row is not None and int(row["v"]) == SCHEMA_VERSION
    except sqlite3.DatabaseError:
        # the old table shape can even reject the new index statements
        con, ok = None, False
    if not ok:
        if con is not None:
            con.close()
        # an older cache layout cannot be migrated in place; rebuild it
        _remove_db()
        con = _open(CACHE_DB)
        con.execute(
            "INSERT OR REPLACE INTO meta VALUES ('schema', ?)", (str(SCHEMA_VERSION),)
        )
        con.commit()
    return con


def open_cache() -> sqlite3.Connection | None:
    """read-side open for the cli: never rebuilds, never blocks for a minute."""
    if not CACHE_DB.exists():
        print(
            f"no index at {CACHE_DB} — run `ccbrowse.py` once to build it",
            file=sys.stderr,
        )
        return None
    try:
        con = _open(CACHE_DB)
        row = con.execute("SELECT v FROM meta WHERE k = 'schema'").fetchone()
        if row is not None and int(row["v"]) == SCHEMA_VERSION:
            return con
        con.close()
    except sqlite3.DatabaseError:
        pass
    print(
        "index was built by an older schema — run `ccbrowse.py` to rebuild it",
        file=sys.stderr,
    )
    return None


def warn_if_stale(con: sqlite3.Connection) -> None:
    """say so on stderr, but still answer from whatever is cached."""
    known = {
        r["path"]: (r["mtime"], r["size"])
        for r in con.execute("SELECT path, mtime, size FROM sessions")
    }
    files = session_files()
    changed = 0
    for p in files:
        try:
            st = p.stat()
        except OSError:
            continue
        if known.get(str(p)) != (int(st.st_mtime), st.st_size):
            changed += 1
    if changed:
        print(
            f"index is stale: {changed} of {len(files)} logs changed since it was"
            " built — answering from the cache anyway",
            file=sys.stderr,
        )


def session_files() -> list[Path]:
    """every log: top-level sessions plus the subagent transcripts beneath them."""
    if not PROJECTS.is_dir():
        return []
    out: list[Path] = []
    for d in PROJECTS.iterdir():
        if not d.is_dir():
            continue
        out.extend(d.glob("*.jsonl"))
        out.extend(d.glob("*/**/*.jsonl"))
    return out


def reindex(con: sqlite3.Connection, quiet: bool = False) -> int:
    files = session_files()
    known = {
        r["path"]: (r["mtime"], r["size"], r["session_id"])
        for r in con.execute("SELECT path, mtime, size, session_id FROM sessions")
    }
    stale, live = [], set()
    for p in files:
        sp = str(p)
        live.add(sp)
        try:
            st = p.stat()
        except OSError:
            continue
        if known.get(sp, (None, None, None))[:2] != (int(st.st_mtime), st.st_size):
            stale.append(sp)

    gone = set(known) - live
    if gone:
        con.executemany("DELETE FROM sessions WHERE path = ?", [(g,) for g in gone])
        _fts_drop(con, [known[g][2] for g in gone])

    if not stale:
        con.commit()
        return 0

    if not quiet:
        print(f"indexing {len(stale)} of {len(files)} logs...", flush=True)

    # one scan clears every stale session's rows; per-session deletes would each
    # walk the whole fts table
    _fts_drop(
        con,
        [known[s][2] for s in stale if s in known]
        + [file_identity(Path(s))[1] for s in stale if s not in known],
    )

    sql = f"INSERT OR REPLACE INTO sessions VALUES ({','.join('?' * len(COLUMNS))})"
    fts_sql = "INSERT INTO msg_fts (text, session_id, role, seq) VALUES (?, ?, ?, ?)"
    done = 0
    batch: list[tuple] = []
    fts_batch: list[tuple] = []
    workers = min(os.cpu_count() or 4, 12)

    with ProcessPoolExecutor(max_workers=workers) as pool:
        for rec in pool.map(scan_file, stale, chunksize=8):
            done += 1
            if rec is None:
                continue
            docs = rec.pop("_docs")
            batch.append(tuple(rec[c] for c in COLUMNS))
            sid = rec["session_id"]
            fts_batch.extend((t, sid, role, seq) for role, seq, t in docs)
            if len(batch) >= 150:
                con.executemany(sql, batch)
                con.executemany(fts_sql, fts_batch)
                con.commit()
                batch.clear()
                fts_batch.clear()
            if not quiet and done % 250 == 0:
                print(f"  {done}/{len(stale)}", flush=True)
        if batch:
            con.executemany(sql, batch)
            con.executemany(fts_sql, fts_batch)
    con.commit()
    return len(stale)


def _fts_drop(con: sqlite3.Connection, session_ids: list[str]) -> None:
    if not session_ids:
        return
    for i in range(0, len(session_ids), 500):
        chunk = session_ids[i : i + 500]
        con.execute(
            f"DELETE FROM msg_fts WHERE session_id IN ({','.join('?' * len(chunk))})",
            chunk,
        )


_vec_state: dict = {"matrix": None, "rows": None, "model": None, "fingerprint": None}


def _fingerprint(con) -> str:
    r = con.execute(
        "SELECT COUNT(*) c, COALESCE(MAX(mtime), 0) m FROM sessions"
    ).fetchone()
    n = con.execute("SELECT COUNT(*) FROM msg_fts").fetchone()[0]
    return f"{r['c']}-{r['m']}-{n}"


def get_model():
    if _vec_state["model"] is None:
        _vec_state["model"] = StaticModel.from_pretrained(EMBED_MODEL)
    return _vec_state["model"]


def build_vectors(con, quiet: bool = False) -> int:
    """embed every indexed message; cheap enough to redo wholesale on change."""
    if not SEMANTIC_OK:
        return 0
    fp = _fingerprint(con)
    meta = con.execute("SELECT v FROM meta WHERE k = 'vec_fp'").fetchone()
    if meta and meta["v"] == fp and VEC_FILE.exists():
        return 0

    rows = con.execute(
        "SELECT rowid, text FROM msg_fts ORDER BY rowid"
    ).fetchall()
    if not rows:
        return 0
    if not quiet:
        print(f"embedding {len(rows)} messages...", flush=True)

    model = get_model()
    # the tail of a long message rarely changes its topic; cap for speed
    vecs = model.encode([r["text"][:1200] for r in rows], show_progress_bar=False)
    vecs = np.asarray(vecs, dtype=np.float32)
    norms = np.linalg.norm(vecs, axis=1, keepdims=True)
    vecs /= np.maximum(norms, 1e-9)
    # write-then-rename: a reader holding the old file mmap'd keeps reading the
    # old inode instead of seeing a half-written matrix
    # (the name must still end in .npy or numpy appends it)
    tmp = VEC_FILE.with_name("vectors.tmp.npy")
    np.save(tmp, vecs)
    os.replace(tmp, VEC_FILE)

    con.execute("DROP TABLE IF EXISTS vec_rows")
    con.execute("CREATE TABLE vec_rows (i INTEGER PRIMARY KEY, rid INTEGER)")
    con.executemany(
        "INSERT INTO vec_rows VALUES (?, ?)",
        [(i, r["rowid"]) for i, r in enumerate(rows)],
    )
    con.execute("INSERT OR REPLACE INTO meta VALUES ('vec_fp', ?)", (fp,))
    con.commit()
    _vec_state.update(matrix=None, rows=None, fingerprint=None)
    return len(rows)


def load_vectors(con):
    if not SEMANTIC_OK:  # numpy is absent; a hand-crafted mode=semantic must not 500
        return None, None
    fp = _fingerprint(con)
    if _vec_state["matrix"] is not None and _vec_state["fingerprint"] == fp:
        return _vec_state["matrix"], _vec_state["rows"]
    if not VEC_FILE.exists():
        return None, None
    matrix = np.load(VEC_FILE, mmap_mode="r")
    rows = [r["rid"] for r in con.execute("SELECT rid FROM vec_rows ORDER BY i")]
    if len(rows) != matrix.shape[0]:
        return None, None
    _vec_state.update(matrix=matrix, rows=rows, fingerprint=fp)
    return matrix, rows


def subagent_parents(con) -> dict[str, str]:
    """subagent row id -> the session that spawned it, for rolling hits up."""
    return {
        r["session_id"]: r["parent_id"]
        for r in con.execute(
            "SELECT session_id, parent_id FROM sessions"
            " WHERE kind = 'subagent' AND parent_id != ''"
        )
    }


def semantic_hits(con, q: str, pool: int = 600) -> dict[str, dict]:
    """query -> {session_id: {score, snippet, n_hits}} over the whole corpus.

    a hit inside a subagent transcript is reported against its parent session,
    flagged `via_subagent`, since the subagent is not a browsable row.
    """
    matrix, rows = load_vectors(con)
    if matrix is None:
        return {}
    parents = subagent_parents(con)
    qv = np.asarray(get_model().encode([q])[0], dtype=np.float32)
    qv /= max(float(np.linalg.norm(qv)), 1e-9)
    scores = matrix @ qv
    take = min(pool, scores.shape[0])
    top = np.argpartition(-scores, take - 1)[:take]
    top = top[np.argsort(-scores[top])]

    out: dict[str, dict] = {}
    for i in top:
        score = float(scores[i])
        if score < 0.15:  # below this the nearest neighbour is just noise
            break
        row = con.execute(
            "SELECT session_id, text FROM msg_fts WHERE rowid = ?", (rows[int(i)],)
        ).fetchone()
        if row is None:
            continue
        raw_sid = row["session_id"]
        sid = parents.get(raw_sid, raw_sid)
        via = 1 if raw_sid in parents else 0
        if sid in out:
            out[sid]["n_hits"] += 1
            out[sid]["via_subagent"] |= via
        else:
            text = " ".join(row["text"].split())
            out[sid] = {
                "score": score,
                "snip": text[:260] + ("…" if len(text) > 260 else ""),
                "n_hits": 1,
                "via_subagent": via,
            }
    return out


def fts_query(q: str) -> str:
    """user text -> a MATCH expression that cannot be a syntax error."""
    quoted = re.findall(r'"([^"]+)"', q)
    rest = re.sub(r'"[^"]+"', " ", q)
    terms = [f'"{p}"' for p in quoted]
    for tok in re.findall(r"[\w#@./-]+", rest, re.UNICODE):
        tok = tok.replace('"', "")
        if tok:
            terms.append(f'"{tok}"*')
    return " ".join(terms)


# subagent rows exist only to be searched; they are never listed on their own
BASE_FILTERS = ["kind = 'session'", "sidechain = 0", "(n_user + n_assistant) > 0"]

# a pasted session id, or the 8-char prefix `list`/`search` print
_SESSION_ID = re.compile(r"[0-9a-f]{8}[0-9a-f-]*", re.IGNORECASE)


def id_lookup(con, q: str, cols: str) -> list:
    """rows whose session id starts with `q`, or [] if `q` is not id-shaped.

    the project/branch facets are deliberately not applied: an id names one
    conversation, and a filter left over from browsing should not hide it. the
    regex admits only hex and dashes, so `q` can carry no LIKE wildcard.
    """
    q = q.strip()
    if not _SESSION_ID.fullmatch(q):
        return []
    return con.execute(
        f"SELECT {cols} FROM sessions s"
        f" WHERE {' AND '.join(BASE_FILTERS)} AND s.session_id LIKE ?"
        " ORDER BY s.modified DESC LIMIT 20",
        (q + "%",),
    ).fetchall()


# already qualified with the `s` alias: an expression cannot take one as a
# prefix, so `ORDER BY s.` + the value would be a syntax error for the counts
SORTS = {
    "recent": "s.modified DESC",
    "oldest": "s.modified ASC",
    "longest": "(s.n_user + s.n_assistant) DESC",
    "shortest": "(s.n_user + s.n_assistant) ASC",
}


def _filters(project: str, branch: str, since: str, titled: str) -> tuple[str, list]:
    where = list(BASE_FILTERS)
    args: list = []
    if project:
        where.append("project = ?")
        args.append(project)
    if branch:
        where.append("branch = ?")
        args.append(branch)
    if since:
        where.append("modified >= ?")
        args.append(since)
    if titled == "1":
        where.append("(custom_title != '' OR ai_title != '' OR summary != '')")
    return " AND ".join(where), args


def _shape(d: dict) -> dict:
    """one raw result row -> what the api hands back."""
    d["tail"] = json.loads(d["tail"] or "[]")
    d["titled"] = bool(d.pop("custom_title") or d.pop("ai_title") or d.pop("summary"))
    d["via_subagent"] = 1 if d.pop("n_via", d.get("via_subagent", 0)) else 0
    d.pop("score", None)
    return d


def list_sessions(
    con, q="", project="", branch="", since="", titled="", mode="meta",
    sort="recent", limit=100, offset=0,
) -> dict:
    clause, args = _filters(project, branch, since, titled)
    order = SORTS.get(sort, SORTS["recent"])
    cols = (
        "s.session_id, s.project, s.branch, s.title, s.custom_title, s.ai_title,"
        " s.summary, s.first_prompt, s.created, s.modified, s.day, s.n_user,"
        " s.n_assistant, s.n_tool, s.size, s.tail"
    )

    # an id is an identity, not a phrase: it resolves in every mode, and only
    # falls through to a text search when it matches no conversation
    if q:
        found = id_lookup(con, q, cols)
        if found:
            return {
                "total": len(found),
                "sessions": [_shape(dict(r)) for r in found],
                "mode": "id",
            }

    if q and mode == "semantic":
        hits = semantic_hits(con, q)
        if not hits:
            return {"total": 0, "sessions": [], "mode": mode}
        ids = list(hits)
        placeholders = ",".join("?" * len(ids))
        rows = con.execute(
            f"SELECT {cols} FROM sessions s"
            f" WHERE {clause} AND s.session_id IN ({placeholders})",
            [*args, *ids],
        ).fetchall()
        merged = []
        for r in rows:
            d = dict(r)
            d.update(hits[d["session_id"]])
            merged.append(d)
        if sort in ("relevance", "recent"):
            # relevance is the only ordering that makes sense for a fuzzy match
            merged.sort(key=lambda d: -d["score"])
        elif sort in ("longest", "shortest"):
            merged.sort(
                key=lambda d: d["n_user"] + d["n_assistant"],
                reverse=sort == "longest",
            )
        else:
            merged.sort(key=lambda d: d["modified"], reverse=sort != "oldest")
        page = merged[offset : offset + limit]
        return {
            "total": len(merged),
            "sessions": [_shape(d) for d in page],
            "mode": mode,
        }

    if q and mode == "content":
        match = fts_query(q)
        if not match:
            return {"total": 0, "sessions": [], "mode": mode}
        rank = "score ASC" if sort == "relevance" else order
        # bm25()/snippet() only work in a direct scan of the fts table, so rank
        # and extract there first, then aggregate in an outer query. with MIN(),
        # sqlite takes the bare `snip` from the row that produced the minimum.
        # MATERIALIZED is required: an inlined cte loses the fts context and
        # sqlite raises "unable to use function bm25 in the requested context".
        # `owner` maps a hit's row back to a listable session: a hit inside a
        # subagent transcript counts for the session that spawned it. summing
        # `via` (rather than MAX) keeps MIN(score) the query's only min/max
        # aggregate, which is what lets the bare `snip` come from the best row.
        owner = (
            "  SELECT CASE WHEN m.kind = 'subagent' THEN m.parent_id ELSE raw.sid END"
            "    AS session_id,"
            "    CASE WHEN m.kind = 'subagent' THEN 1 ELSE 0 END AS via,"
            "    raw.score, raw.snip"
            "  FROM raw JOIN sessions m ON m.session_id = raw.sid"
        )
        sql = (
            f"WITH raw AS MATERIALIZED ("
            f"  SELECT session_id AS sid, bm25(msg_fts) AS score,"
            f"    snippet(msg_fts, 0, '\x02', '\x03', '…', 14) AS snip"
            f"  FROM msg_fts WHERE msg_fts MATCH ?),"
            f" mapped AS ({owner}),"
            f" hits AS ("
            f"  SELECT session_id, MIN(score) AS score, COUNT(*) AS n_hits,"
            f"    SUM(via) AS n_via, snip"
            f"  FROM mapped GROUP BY session_id)"
            f" SELECT {cols}, h.n_hits, h.snip, h.score, h.n_via"
            f" FROM hits h JOIN sessions s ON s.session_id = h.session_id"
            f" WHERE {clause} ORDER BY {rank} LIMIT ? OFFSET ?"
        )
        count_sql = (
            f"WITH raw AS MATERIALIZED ("
            f"  SELECT DISTINCT session_id AS sid FROM msg_fts WHERE msg_fts MATCH ?),"
            f" hits AS (SELECT DISTINCT"
            f"   CASE WHEN m.kind = 'subagent' THEN m.parent_id ELSE raw.sid END"
            f"   AS session_id FROM raw JOIN sessions m ON m.session_id = raw.sid)"
            f" SELECT COUNT(*) FROM hits h JOIN sessions s ON s.session_id = h.session_id"
            f" WHERE {clause}"
        )
        try:
            total = con.execute(count_sql, [match, *args]).fetchone()[0]
            rows = con.execute(sql, [match, *args, limit, offset]).fetchall()
        except sqlite3.OperationalError as exc:
            return {"total": 0, "sessions": [], "mode": mode, "error": str(exc)}
    else:
        if q:
            clause += (
                " AND (s.title LIKE ? OR s.first_prompt LIKE ?"
                " OR s.project LIKE ? OR s.branch LIKE ?)"
            )
            args = [*args, *([f"%{q}%"] * 4)]
        total = con.execute(
            f"SELECT COUNT(*) FROM sessions s WHERE {clause}", args
        ).fetchone()[0]
        rows = con.execute(
            f"SELECT {cols} FROM sessions s WHERE {clause}"
            f" ORDER BY {order} LIMIT ? OFFSET ?",
            [*args, limit, offset],
        ).fetchall()

    return {
        "total": total,
        "sessions": [_shape(dict(r)) for r in rows],
        "mode": mode,
    }


def facets(con, project="") -> dict:
    projects = [
        {"value": r["project"], "n": r["n"]}
        for r in con.execute(
            f"SELECT project, COUNT(*) n FROM sessions s WHERE {' AND '.join(BASE_FILTERS)}"
            " GROUP BY project ORDER BY n DESC"
        )
    ]
    bargs = []
    bclause = " AND ".join(BASE_FILTERS) + " AND branch != ''"
    if project:
        bclause += " AND project = ?"
        bargs.append(project)
    branches = [
        {"value": r["branch"], "n": r["n"]}
        for r in con.execute(
            f"SELECT branch, COUNT(*) n FROM sessions s WHERE {bclause}"
            " GROUP BY branch ORDER BY n DESC LIMIT 60",
            bargs,
        )
    ]
    tot = con.execute(
        f"SELECT COUNT(*) c, SUM(n_user + n_assistant) m, MIN(day) f"
        f" FROM sessions s WHERE {' AND '.join(BASE_FILTERS)}"
    ).fetchone()
    return {
        "projects": projects,
        "branches": branches,
        "stats": {"sessions": tot["c"], "messages": tot["m"] or 0, "since": tot["f"]},
        "semantic": SEMANTIC_OK and VEC_FILE.exists(),
    }


def agent_tool_calls(path: Path) -> dict[str, str]:
    """agent id -> the id of the Task tool call that spawned it, where the log says.

    two places record the link: the `progress` frames streamed from a running
    subagent (`data.agentId` + `parentToolUseID`) and the final tool_result the
    parent receives (`toolUseResult.agentId`). agents that were not dispatched
    through a tool call at all — warmups, and named team agents — appear in
    neither, so they simply have no id here.
    """
    out: dict[str, str] = {}
    try:
        fh = path.open("r", encoding="utf-8", errors="replace")
    except OSError:
        return out
    with fh:
        for line in fh:
            if '"agentId"' not in line:
                continue
            try:
                d = json.loads(line)
            except json.JSONDecodeError:
                continue
            data = d.get("data")
            if d.get("type") == "progress" and isinstance(data, dict):
                aid, tid = data.get("agentId"), d.get("parentToolUseID")
                if aid and tid:
                    out.setdefault(aid, tid)
            res = d.get("toolUseResult")
            if isinstance(res, dict) and res.get("agentId"):
                msg = d.get("message")
                content = msg.get("content") if isinstance(msg, dict) else None
                if isinstance(content, list):
                    for b in content:
                        if isinstance(b, dict) and b.get("type") == "tool_result":
                            if b.get("tool_use_id"):
                                out[res["agentId"]] = b["tool_use_id"]
    return out


def subagents_of(con, session_id: str, path: str = "") -> list[dict]:
    rows = con.execute(
        "SELECT session_id, agent_id, agent_type, agent_name, model, spawn_depth,"
        " parent_agent_id, tool_use_id, title, n_user, n_assistant, created"
        " FROM sessions WHERE kind = 'subagent' AND parent_id = ?"
        " AND (n_user + n_assistant) > 0 ORDER BY created, session_id",
        (session_id,),
    ).fetchall()
    if not rows:
        return []
    # the sidecar states the spawning call outright; only fall back to reading
    # it out of the parent transcript for the agents whose sidecar is missing
    links = (
        agent_tool_calls(Path(path))
        if path and any(not r["tool_use_id"] for r in rows)
        else {}
    )
    return [
        {
            "id": r["session_id"],
            "agent_id": r["agent_id"],
            "agent_type": r["agent_type"],
            "agent_name": r["agent_name"],
            "model": r["model"],
            "spawn_depth": r["spawn_depth"],
            "parent_agent_id": r["parent_agent_id"],
            "title": r["title"],
            "n_events": r["n_user"] + r["n_assistant"],
            "started": r["created"],
            "tool_use_id": r["tool_use_id"] or links.get(r["agent_id"], ""),
        }
        for r in rows
    ]


def full_session(con, session_id: str) -> dict:
    row = con.execute(
        "SELECT * FROM sessions WHERE session_id = ?", (session_id,)
    ).fetchone()
    if row is None:
        return {"error": "not found"}

    events = []
    try:
        fh = Path(row["path"]).open("r", encoding="utf-8", errors="replace")
    except OSError as exc:
        return {"error": str(exc)}
    with fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                d = json.loads(line)
            except json.JSONDecodeError:
                continue
            if d.get("type") not in ("user", "assistant"):
                continue
            msg = d.get("message")
            if not isinstance(msg, dict):
                continue
            role = d["type"]
            for kind, text, block in message_blocks(msg):
                if not text:
                    continue
                if kind == "text" and role == "user":
                    text = clean_prompt(text)
                    if not text:
                        continue
                ev = {
                    "role": role,
                    "kind": kind,
                    "text": text[:20000],
                    "ts": d.get("timestamp", ""),
                }
                if kind == "tool" and block.get("id"):
                    # lets the ui line a Task call up with its subagent transcript
                    ev["tool_use_id"] = block["id"]
                    ev["tool"] = block.get("name", "")
                events.append(ev)
    meta = {k: row[k] for k in row.keys() if k != "tail"}
    out = {"meta": meta, "events": events}
    if row["kind"] == "session":
        out["subagents"] = subagents_of(con, session_id, row["path"])
    return out


def mark_indexed(con) -> None:
    stamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    con.execute("INSERT OR REPLACE INTO meta VALUES ('indexed_at', ?)", (stamp,))
    con.commit()


def status(con) -> dict:
    n = con.execute(
        f"SELECT COUNT(*) FROM sessions s WHERE {' AND '.join(BASE_FILTERS)}"
    ).fetchone()[0]
    n_sub = con.execute(
        "SELECT COUNT(*) FROM sessions WHERE kind = 'subagent'"
    ).fetchone()[0]
    row = con.execute("SELECT v FROM meta WHERE k = 'indexed_at'").fetchone()
    return {
        "n_sessions": n,
        "n_subagents": n_sub,
        "n_messages": con.execute("SELECT COUNT(*) FROM msg_fts").fetchone()[0],
        "fingerprint": _fingerprint(con),
        "indexed_at": row["v"] if row else "",
        "semantic": SEMANTIC_OK and VEC_FILE.exists(),
    }


def refresh_loop(stop: threading.Event, interval: int, embed: bool) -> None:
    """keep the index warm while the server runs, on its own connection.

    WAL means this writer never blocks the request threads' reads, so it does
    not take Handler.lock; the request side picks up new rows on its next
    statement, and the embedding cache invalidates itself off the fingerprint.
    """
    con = connect()
    try:
        while not stop.wait(interval):
            try:
                n = reindex(con, quiet=True)
                if n:
                    if embed and SEMANTIC_OK:
                        build_vectors(con, quiet=True)
                    mark_indexed(con)
            except Exception as exc:  # a bad scan must not kill the refresher
                print(f"refresh failed: {type(exc).__name__}: {exc}", file=sys.stderr)
    finally:
        con.close()


class Handler(BaseHTTPRequestHandler):
    con: sqlite3.Connection
    lock = threading.Lock()

    def log_message(self, *_args):
        pass  # keep the terminal clean

    def _send(self, code, body: bytes, ctype="application/json"):
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body)

    def _json(self, obj, code=200):
        self._send(code, json.dumps(obj).encode(), "application/json")

    def do_GET(self):
        url = urlparse(self.path)
        qs = parse_qs(url.query)
        one = lambda k, d="": qs.get(k, [d])[0]  # noqa: E731

        try:
            if url.path == "/":
                self._send(200, UI_FILE.read_bytes(), "text/html; charset=utf-8")
            elif url.path == "/api/sessions":
                with self.lock:
                    data = list_sessions(
                        self.con,
                        q=one("q"),
                        project=one("project"),
                        branch=one("branch"),
                        since=one("since"),
                        titled=one("titled"),
                        mode=one("mode", "meta"),
                        sort=one("sort", "recent"),
                        limit=min(int(one("limit", "100")), 300),
                        offset=int(one("offset", "0")),
                    )
                self._json(data)
            elif url.path == "/api/facets":
                with self.lock:
                    self._json(facets(self.con, project=one("project")))
            elif url.path.startswith("/api/session/"):
                sid = unquote(url.path.rsplit("/", 1)[-1])
                with self.lock:
                    self._json(full_session(self.con, sid))
            elif url.path.startswith("/api/subagent/"):
                sid = unquote(url.path.rsplit("/", 1)[-1])
                with self.lock:
                    self._json(full_session(self.con, sid))
            elif url.path == "/api/status":
                with self.lock:
                    self._json(status(self.con))
            elif url.path == "/api/refresh":
                with self.lock:
                    n = reindex(self.con, quiet=True)
                    if n:
                        mark_indexed(self.con)
                self._json({"reindexed": n})
            else:
                self._json({"error": "not found"}, 404)
        except BrokenPipeError:
            pass
        except Exception as exc:  # surface errors in the UI instead of hanging
            self._json({"error": f"{type(exc).__name__}: {exc}"}, 500)


SUBCOMMANDS = ("search", "show", "list")


def _fmt_row(d: dict) -> str:
    bits = [f"{d['session_id'][:8]}  {d['modified'][:16].replace('T', ' ')}"]
    n = d["n_user"] + d["n_assistant"]
    bits.append(f"{n:>4} msg")
    if d.get("n_hits"):
        bits.append(f"{d['n_hits']:>3} hit" + ("s" if d["n_hits"] != 1 else " "))
    if d.get("via_subagent"):
        bits.append("via subagent")
    return "  ".join(bits) + f"\n    {d['title'][:110]}\n    {d['project']}"


def cli(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(prog="ccbrowse.py", description="query the index")
    sub = ap.add_subparsers(dest="cmd", required=True)

    s = sub.add_parser("search", help="search the indexed conversations")
    s.add_argument("query")
    s.add_argument("--mode", choices=("meta", "content", "semantic"), default="content")
    s.add_argument("--project", default="")
    s.add_argument("--limit", type=int, default=20)
    s.add_argument("--json", action="store_true")

    sh = sub.add_parser("show", help="print one session or subagent transcript")
    sh.add_argument("session_id")
    sh.add_argument("--json", action="store_true")

    ls = sub.add_parser("list", help="list the most recent sessions")
    ls.add_argument("--project", default="")
    ls.add_argument("--limit", type=int, default=20)
    ls.add_argument("--json", action="store_true")

    args = ap.parse_args(argv)
    con = open_cache()
    if con is None:
        return 1
    warn_if_stale(con)

    if args.cmd == "show":
        data = full_session(con, args.session_id)
        if args.json:
            print(json.dumps(data, indent=2))
            return 0 if "error" not in data else 1
        if "error" in data:
            print(data["error"], file=sys.stderr)
            return 1
        m = data["meta"]
        print(f"{m['title']}\n{m['session_id']}  {m['project']}  {m['modified'][:16]}")
        for sa in data.get("subagents", []):
            print(f"  subagent {sa['id']}  {sa['n_events']:>4} msg  {sa['title'][:70]}")
        print()
        for ev in data["events"]:
            print(f"[{ev['role']}/{ev['kind']}] {ev['text'][:2000]}\n")
        return 0

    if args.cmd == "list":
        data = list_sessions(con, project=args.project, limit=args.limit)
    else:
        if args.mode == "semantic" and not (SEMANTIC_OK and VEC_FILE.exists()):
            print(
                "semantic mode needs model2vec and a built vector index; falling"
                " back to full text",
                file=sys.stderr,
            )
            args.mode = "content"
        data = list_sessions(
            con, q=args.query, mode=args.mode, project=args.project, limit=args.limit
        )

    if args.json:
        print(json.dumps(data, indent=2))
        return 0
    if data.get("error"):
        print(data["error"], file=sys.stderr)
        return 1
    print(f"{data['total']} match(es), showing {len(data['sessions'])}\n")
    for d in data["sessions"]:
        print(_fmt_row(d) + "\n")
    return 0


def main() -> int:
    if len(sys.argv) > 1 and sys.argv[1] in SUBCOMMANDS:
        return cli(sys.argv[1:])

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--port", type=int, default=4173)
    ap.add_argument("--reindex", action="store_true", help="discard the cache first")
    ap.add_argument("--no-open", action="store_true")
    ap.add_argument("--no-embed", action="store_true", help="skip semantic indexing")
    ap.add_argument(
        "--no-refresh", action="store_true", help="do not re-index while serving"
    )
    ap.add_argument("--refresh-secs", type=int, default=REFRESH_SECS)
    args = ap.parse_args()

    con = connect(reset=args.reindex)
    reindex(con)
    if SEMANTIC_OK and not args.no_embed:
        build_vectors(con)
    elif not SEMANTIC_OK:
        print("semantic search off (no model2vec) — run with `uv run ccbrowse.py`")
    mark_indexed(con)
    total = con.execute(
        f"SELECT COUNT(*) FROM sessions s WHERE {' AND '.join(BASE_FILTERS)}"
    ).fetchone()[0]

    Handler.con = con
    server = ThreadingHTTPServer(("127.0.0.1", args.port), Handler)
    url = f"http://localhost:{args.port}"
    print(f"{total} sessions ready at {url}", flush=True)

    stop = threading.Event()
    if not args.no_refresh:
        threading.Thread(
            target=refresh_loop,
            args=(stop, max(5, args.refresh_secs), not args.no_embed),
            daemon=True,
        ).start()
    if not args.no_open:
        threading.Timer(0.4, lambda: webbrowser.open(url)).start()
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print()
    finally:
        stop.set()
    return 0


if __name__ == "__main__":
    sys.exit(main())
