#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["model2vec>=0.9", "numpy"]
# ///
"""browse claude code conversations in a browser.

reads ~/.claude/projects/*/*.jsonl, builds a cached index, serves a local UI.
titles come from a user-set `custom-title`, else an `ai-title` record (what
/resume shows), else a `summary` record, else a cleaned first user prompt.
subagent transcripts under <project>/<session-id>/subagents/ are indexed too,
so search reaches delegated work and reports it against its parent session.

usage:
    ./ccbrowse.py              # index (incremental) and serve on :4173
    ./ccbrowse.py --port 8080
    ./ccbrowse.py --reindex    # throw away the cache first
    ./ccbrowse.py search foo --json
    ./ccbrowse.py list --limit 5
    ./ccbrowse.py show <session-id>
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sqlite3
import sys
import threading
import webbrowser
from concurrent.futures import ProcessPoolExecutor
from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

PROJECTS = Path.home() / ".claude" / "projects"
CACHE_DB = Path.home() / ".cache" / "cc-browse" / "index.db"
VEC_FILE = CACHE_DB.parent / "vectors.npy"
UI_FILE = Path(__file__).parent / "ui.html"
UI_DIR = Path(__file__).parent / "ui"

SCHEMA_VERSION = 9

# how often the background thread re-runs the incremental index
REFRESH_SECS = 60

# a log written to within this many seconds is treated as a live agent. it has
# to clear REFRESH_SECS: the indexed `modified` lags a growing file by up to one
# refresh pass, so liveness is decided from a fresh stat, not from the row.
ACTIVE_SECS = 90

# static embeddings: a token-lookup distillation, no transformer forward pass.
# ~0.03 ms/message, which is what makes indexing the whole corpus practical.
EMBED_MODEL = "minishlab/potion-base-8M"
try:
    import numpy as np
    from model2vec import StaticModel

    SEMANTIC_OK = True
except ImportError:  # optional; the ui hides the mode when it is missing
    SEMANTIC_OK = False

# how many trailing messages to keep in the index for the list preview
TAIL_KEEP = 6
TAIL_CHARS = 400
# per-message cap for the searchable text index
FTS_CHARS = 4000

# noise wrappers that make a first prompt unreadable as a title
_STRIP_BLOCKS = re.compile(
    r"<(system-reminder|local-command-stdout|command-args|command-contents)>.*?</\1>",
    re.S,
)
_CMD_NAME = re.compile(r"<command-name>\s*(.*?)\s*</command-name>", re.S)
_CMD_MSG = re.compile(r"</?command-message>", re.S)
_ANY_TAG = re.compile(r"<[^>]{1,60}>")
# a wrapper with attributes blows past the 60-char cap above — subagent prompts
# arrive inside one of these, so the tag would otherwise become the title
_ATTR_TAG = re.compile(r"</?[a-zA-Z][\w-]*(?:\s+[\w-]+=\"[^\"]*\")*\s*/?>")
# claude code prepends this to messages produced by local command output
_CAVEAT = re.compile(
    r"Caveat: The messages below were generated by the user while running local"
    r" commands\. DO NOT.*?(?=$|\n)",
    re.S,
)
# a message from another claude session is delivered as a plain `type=user`
# line whose metadata is byte-identical to a typed prompt — no isMeta, no
# marker field. the wrapper around the payload is the only signal there is.
_INBOUND = re.compile(
    r"<(teammate|agent|cross-session)-message\b([^>]*)>(.*?)</\1-message>", re.S
)
_INBOUND_HEAD = re.compile(r"^\s*(?:Another Claude session sent a message:\s*)?<")
_INBOUND_ATTR = re.compile(r"([\w-]+)=\"([^\"]*)\"")
# the attributes the three wrapper flavours name their sender with, best first
_SENDER_KEYS = ("teammate_id", "from-name", "from", "name")


def inbound_message(text: str) -> tuple[str, str] | None:
    """(sender, payload) when a user turn is really a message from another session.

    None for anything typed by the actual user. The wrapper has to open the
    message — a quoted one further down is somebody talking *about* a teammate
    message, not one being delivered.
    """
    if not text or "-message" not in text:
        return None
    if not _INBOUND_HEAD.match(text):
        return None
    parts = list(_INBOUND.finditer(text))
    if not parts:
        return None
    if parts[0].start() > 60:  # only the one boilerplate line may precede it
        return None
    attrs = dict(_INBOUND_ATTR.findall(parts[0].group(2)))
    sender = next(
        (attrs[k] for k in _SENDER_KEYS if attrs.get(k)), "another claude session"
    )
    payload = "\n\n".join(p.group(3).strip() for p in parts if p.group(3).strip())
    return sender, payload


def clean_prompt(text: str) -> str:
    """turn a raw first user message into something readable as a title."""
    if not text:
        return ""
    text = _CAVEAT.sub(" ", text)
    cmd = _CMD_NAME.search(text)
    body = _STRIP_BLOCKS.sub(" ", text)
    body = _CMD_MSG.sub(" ", body)
    body = _ATTR_TAG.sub(" ", body)
    body = _ANY_TAG.sub(" ", body)
    body = re.sub(r"\s+", " ", body).strip()
    if cmd:
        name = cmd.group(1)
        # a slash command with no extra prose is more useful shown as the command
        return f"{name} {body}".strip() if body and body != name else name
    return body


def block_text(block: dict) -> tuple[str, str]:
    """(kind, text) for one assistant/user content block."""
    kind = block.get("type")
    if kind == "text":
        return "text", block.get("text", "")
    if kind == "thinking":
        return "thinking", block.get("thinking", "")
    if kind == "tool_use":
        name = block.get("name", "tool")
        inp = block.get("input", {})
        if isinstance(inp, dict):
            hint = (
                inp.get("command")
                or inp.get("file_path")
                or inp.get("pattern")
                or inp.get("prompt")
                or inp.get("description")
                or ""
            )
        else:
            hint = str(inp)
        return "tool", f"{name}: {str(hint)[:200]}"
    if kind == "tool_result":
        content = block.get("content", "")
        if isinstance(content, list):
            content = " ".join(
                c.get("text", "") for c in content if isinstance(c, dict)
            )
        return "tool_result", str(content)
    if kind == "image":
        return "image", "[image]"
    return kind or "unknown", ""


def message_blocks(msg: dict) -> list[tuple[str, str, dict]]:
    """(kind, text, raw block) for every content block of a message."""
    content = msg.get("content")
    if isinstance(content, str):
        return [("text", content, {})]
    if isinstance(content, list):
        return [(*block_text(b), b) for b in content if isinstance(b, dict)]
    return []


def message_parts(msg: dict) -> list[tuple[str, str]]:
    return [(k, t) for k, t, _ in message_blocks(msg)]


def file_identity(path: Path) -> tuple[str, str, str, str]:
    """(kind, session_id, parent_id, agent_id) implied by a log's location.

    top-level logs are `<project>/<uuid>.jsonl`; anything deeper is a subagent
    transcript living under `<project>/<owning-uuid>/subagents/...`. subagent
    files carry the *owning session's* id in their own `sessionId` field, so the
    row id has to come from the path or every subagent would collide with it.

    `rel[1]` is the owning session at any nesting depth: a subagent that spawns
    its own subagents does not get a directory of its own — everything it
    spawns is written flat into the same session-level `subagents/` tree — so
    this resolves to the top-level session rather than to an intermediate
    agent. (`parent_agent_id` from the sidecar records the immediate spawner.)
    """
    try:
        rel = path.relative_to(PROJECTS).parts
    except ValueError:
        return "session", path.stem, "", ""
    if len(rel) <= 2:
        return "session", path.stem, "", ""
    parent = rel[1]
    tail = "~".join(rel[2:])[: -len(".jsonl")] if path.suffix == ".jsonl" else "~".join(rel[2:])
    agent = path.stem[len("agent-"):] if path.stem.startswith("agent-") else path.stem
    return "subagent", f"{parent}~{tail}", parent, agent


def read_sidecar(path: Path) -> dict:
    """`<transcript>.meta.json` — what the harness knew when it spawned the agent.

    two thirds of transcripts have one. `description` is a human-written
    one-liner, so it beats anything inferable from the first message, and
    `toolUseId` is the spawning Task call stated outright rather than
    reconstructed from the parent log.
    """
    side = path.with_name(path.stem + ".meta.json")
    try:
        d = json.loads(side.read_text(encoding="utf-8", errors="replace"))
    except (OSError, json.JSONDecodeError):
        return {}
    return d if isinstance(d, dict) else {}


def scan_file(path_str: str) -> dict | None:
    """single pass over one session file, extracting index metadata + search text."""
    path = Path(path_str)
    try:
        st = path.stat()
    except OSError:
        return None

    kind_of_file, session_id, parent_id, agent_id = file_identity(path)
    side = read_sidecar(path) if kind_of_file == "subagent" else {}
    rec = {
        "path": path_str,
        "mtime": int(st.st_mtime),
        "size": st.st_size,
        "session_id": session_id,
        "kind": kind_of_file,
        "parent_id": parent_id,
        "agent_id": agent_id,
        "agent_type": str(side.get("customAgentType") or side.get("agentType") or ""),
        "agent_name": str(side.get("name") or ""),
        "description": str(side.get("description") or ""),
        "model": str(side.get("model") or ""),
        "spawn_depth": int(side.get("spawnDepth") or 0),
        "parent_agent_id": str(side.get("parentAgentId") or ""),
        "tool_use_id": str(side.get("toolUseId") or ""),
        "project": "",
        "branch": "",
        "custom_title": "",
        "ai_title": "",
        "summary": "",
        "first_prompt": "",
        "created": "",
        "modified": "",
        "n_user": 0,
        "n_assistant": 0,
        "n_tool": 0,
        "sidechain": 0,
    }
    # api response id -> (model, in, cache-write 1h, cache-write 5m, cache read, out)
    usage: dict[str, tuple[str, int, int, int, int, int]] = {}
    tail: list[dict] = []
    docs: list[tuple[str, int, str]] = []  # (role, seq, text)
    seq = 0

    try:
        fh = path.open("r", encoding="utf-8", errors="replace")
    except OSError:
        return None

    with fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                d = json.loads(line)
            except json.JSONDecodeError:
                continue
            kind = d.get("type")

            if kind == "custom-title":
                # the user can rename a session repeatedly; the last one wins
                rec["custom_title"] = d.get("customTitle", "") or rec["custom_title"]
                continue
            if kind == "ai-title":
                rec["ai_title"] = d.get("aiTitle", "") or rec["ai_title"]
                continue
            if kind == "summary":
                rec["summary"] = d.get("summary", "") or rec["summary"]
                continue
            if kind not in ("user", "assistant"):
                continue

            if not rec["project"]:
                rec["project"] = d.get("cwd", "") or ""
            if not rec["branch"]:
                rec["branch"] = d.get("gitBranch", "") or ""
            if d.get("isSidechain"):
                rec["sidechain"] = 1
            ts = d.get("timestamp", "")
            if ts:
                if not rec["created"]:
                    rec["created"] = ts
                rec["modified"] = ts

            msg = d.get("message")
            if not isinstance(msg, dict):
                continue

            parts = message_parts(msg)
            rec["n_tool"] += sum(1 for k, _ in parts if k == "tool")
            text = " ".join(t for k, t in parts if k == "text" and t).strip()

            sender = ""
            if kind == "user":
                rec["n_user"] += 1
                # tool results are echoed as user turns; they are not prompts
                is_tool_echo = bool(parts) and all(
                    k in ("tool_result", "image") for k, _ in parts
                )
                if is_tool_echo:
                    continue
                inbound = inbound_message(text)
                if inbound:
                    # another session talking to this one: never the title, and
                    # only the payload is worth indexing — the rest is boilerplate
                    sender, text = inbound
                else:
                    if text and not rec["first_prompt"]:
                        rec["first_prompt"] = clean_prompt(text)[:300]
                    text = clean_prompt(text)
            else:
                rec["n_assistant"] += 1
                # one api response is written to several adjacent lines carrying
                # the *same* totals (repeated, not streaming deltas), so key the
                # usage by response id and let the last write win. only ids with
                # the `msg_` prefix are api responses: client-side `<synthetic>`
                # placeholders (refusals and the like) carry a bare uuid and a
                # usage object they never actually spent.
                mid = str(msg.get("id") or "")
                u = msg.get("usage")
                if mid.startswith("msg_") and isinstance(u, dict):
                    cw = u.get("cache_creation")
                    if isinstance(cw, dict):
                        # a 1h cache write costs 2x base input and a 5m one
                        # 1.25x, so the two kinds cannot share a bucket
                        w1h = int(cw.get("ephemeral_1h_input_tokens") or 0)
                        w5m = int(cw.get("ephemeral_5m_input_tokens") or 0)
                    else:
                        # no split recorded: price the whole write at the cheaper
                        # ttl rather than dropping it
                        w1h, w5m = 0, int(u.get("cache_creation_input_tokens") or 0)
                    usage[mid] = (
                        str(msg.get("model") or ""),
                        int(u.get("input_tokens") or 0),
                        w1h,
                        w5m,
                        int(u.get("cache_read_input_tokens") or 0),
                        int(u.get("output_tokens") or 0),
                    )

            if text:
                seq += 1
                docs.append((kind, seq, text[:FTS_CHARS]))
                entry = {"role": kind, "text": text[:TAIL_CHARS]}
                if sender:
                    # the list preview labels this line with who sent it instead
                    # of "you" — it is not a turn anyone typed in this session
                    entry["sender"] = sender
                tail.append(entry)
                if len(tail) > TAIL_KEEP:
                    tail.pop(0)

    if not rec["project"]:
        # fall back to the encoded directory name when no message carried a cwd
        try:
            encoded = path.relative_to(PROJECTS).parts[0]
        except ValueError:
            encoded = path.parent.name
        rec["project"] = "/" + encoded.lstrip("-").replace("-", "/")
    rec["tail"] = json.dumps(tail)
    by_model: dict[str, dict[str, int]] = {}
    for model, tin, w1h, w5m, cr, out in usage.values():
        b = by_model.setdefault(
            model, {"in": 0, "cw1h": 0, "cw5m": 0, "cr": 0, "out": 0}
        )
        b["in"] += tin
        b["cw1h"] += w1h
        b["cw5m"] += w5m
        b["cr"] += cr
        b["out"] += out
    rec["usage"] = json.dumps(by_model) if by_model else ""
    # a title the user typed outranks anything generated; for a subagent the
    # sidecar's description is the closest thing to one
    rec["title"] = (
        rec["custom_title"]
        or rec["description"]
        or rec["agent_name"]
        or rec["ai_title"]
        or rec["summary"]
        or rec["first_prompt"]
        or "(empty)"
    )
    rec["day"] = (rec["modified"] or "")[:10]
    rec["_docs"] = docs
    return rec


SCHEMA = """
CREATE TABLE IF NOT EXISTS meta (k TEXT PRIMARY KEY, v TEXT);
CREATE TABLE IF NOT EXISTS sessions (
    path TEXT PRIMARY KEY,
    mtime INTEGER, size INTEGER,
    session_id TEXT, kind TEXT, parent_id TEXT, agent_id TEXT,
    agent_type TEXT, agent_name TEXT, description TEXT, model TEXT,
    spawn_depth INTEGER, parent_agent_id TEXT, tool_use_id TEXT,
    project TEXT, branch TEXT,
    custom_title TEXT, ai_title TEXT, summary TEXT, first_prompt TEXT, title TEXT,
    created TEXT, modified TEXT, day TEXT,
    n_user INTEGER, n_assistant INTEGER, n_tool INTEGER, sidechain INTEGER,
    tail TEXT, usage TEXT
);
CREATE INDEX IF NOT EXISTS idx_modified ON sessions(modified DESC);
CREATE INDEX IF NOT EXISTS idx_project ON sessions(project);
CREATE INDEX IF NOT EXISTS idx_sid ON sessions(session_id);
CREATE INDEX IF NOT EXISTS idx_parent ON sessions(parent_id);
CREATE VIRTUAL TABLE IF NOT EXISTS msg_fts USING fts5(
    text, session_id UNINDEXED, role UNINDEXED, seq UNINDEXED,
    tokenize = 'unicode61 remove_diacritics 2'
);
"""

COLUMNS = [
    "path", "mtime", "size", "session_id", "kind", "parent_id", "agent_id",
    "agent_type", "agent_name", "description", "model", "spawn_depth",
    "parent_agent_id", "tool_use_id",
    "project", "branch",
    "custom_title", "ai_title", "summary", "first_prompt", "title",
    "created", "modified", "day",
    "n_user", "n_assistant", "n_tool", "sidechain", "tail", "usage",
]


# usd per million tokens, (base input, output), published list prices. the
# longest matching prefix wins so dated variants of a model resolve to it.
# costs computed from these are notional — a subscription bills against usage
# limits, not per token — and exist to compare one run with another.
PRICES = {
    "claude-fable-5": (10.0, 50.0),
    "claude-mythos-5": (10.0, 50.0),
    "claude-opus-": (5.0, 25.0),
    "claude-sonnet-5": (3.0, 15.0),
    "claude-sonnet-4-6": (3.0, 15.0),
    "claude-sonnet-4-5": (3.0, 15.0),
    "claude-haiku-4-5": (1.0, 5.0),
}
# multipliers on the base input price. a 1h cache write costs 2x and a 5m write
# 1.25x, so lumping the two would misprice whichever kind dominates.
CACHE_WRITE_1H_MULT = 2.0
CACHE_WRITE_5M_MULT = 1.25
CACHE_READ_MULT = 0.1

USAGE_FIELDS = ("in", "cw1h", "cw5m", "cr", "out")


def usage_merge(usages) -> dict[str, dict[str, int]]:
    """several rows' buckets summed into one — a run is lead plus its agents."""
    out: dict[str, dict[str, int]] = {}
    for j in usages:
        for model, b in _usage_buckets(j).items():
            t = out.setdefault(model, {k: 0 for k in USAGE_FIELDS})
            for k in USAGE_FIELDS:
                t[k] += int(b.get(k) or 0)
    return out


def is_active(path: str) -> bool:
    """was this transcript written to just now? (a running agent)"""
    try:
        return (datetime.now(timezone.utc).timestamp() - os.stat(path).st_mtime) < ACTIVE_SECS
    except OSError:
        return False


def _price_for(model: str) -> tuple[float, float] | None:
    best: tuple[float, float] | None = None
    best_len = -1
    for prefix, price in PRICES.items():
        if model.startswith(prefix) and len(prefix) > best_len:
            best, best_len = price, len(prefix)
    return best


def _usage_buckets(usage) -> dict[str, dict[str, int]]:
    """the stored json blob, or an already-parsed one, as per-model buckets."""
    if isinstance(usage, dict):
        return usage
    try:
        d = json.loads(usage or "{}")
    except json.JSONDecodeError:
        return {}
    return d if isinstance(d, dict) else {}


def usage_totals(usage) -> dict[str, int]:
    """the per-model buckets summed into one figure per token kind."""
    out = {k: 0 for k in USAGE_FIELDS}
    for b in _usage_buckets(usage).values():
        for k in USAGE_FIELDS:
            out[k] += int(b.get(k) or 0)
    out["total"] = sum(out[k] for k in USAGE_FIELDS)
    return out


def usage_cost(usage) -> float | None:
    """usd for these buckets, or None when any model in them has no price.

    None rather than a partial sum: a figure that silently omits one model is
    worse than showing the tokens with no cost beside them.
    """
    buckets = _usage_buckets(usage)
    if not buckets:
        return None
    total = 0.0
    for model, b in buckets.items():
        price = _price_for(model)
        if price is None:
            return None
        base, out_price = price
        total += (
            int(b.get("in") or 0) * base
            + int(b.get("cw1h") or 0) * base * CACHE_WRITE_1H_MULT
            + int(b.get("cw5m") or 0) * base * CACHE_WRITE_5M_MULT
            + int(b.get("cr") or 0) * base * CACHE_READ_MULT
            + int(b.get("out") or 0) * out_price
        )
    return total / 1_000_000


def _cost_sql(alias: str = "s") -> str:
    """`usage_cost` as a scalar subquery, so a row can be sorted or filtered by it.

    The python version stays the authority for what the api reports; this one
    exists because ordering and a threshold have to happen before the page is
    cut, and it must agree with it — including returning NULL when any model in
    the blob has no price, rather than a partial sum that looks cheap.
    Longest-prefix wins by ordering the CASE arms longest first; no price key
    contains a LIKE wildcard, so the prefixes go in unescaped.
    """
    arms = []
    for prefix, (base, out_price) in sorted(PRICES.items(), key=lambda kv: -len(kv[0])):
        rate = " + ".join(
            f"COALESCE(json_extract(e.value, '$.{field}'), 0) * {mult}"
            for field, mult in (
                ("in", base),
                ("cw1h", base * CACHE_WRITE_1H_MULT),
                ("cw5m", base * CACHE_WRITE_5M_MULT),
                ("cr", base * CACHE_READ_MULT),
                ("out", out_price),
            )
        )
        arms.append(f"WHEN e.key LIKE '{prefix}%' THEN ({rate})")
    case = "CASE " + " ".join(arms) + " END"
    # json_each raises on a blank or malformed blob, and COUNT(x) < COUNT(*)
    # means some model fell through the CASE to NULL — the whole sum is void
    return (
        "(SELECT CASE WHEN COUNT(*) = COUNT(x) THEN SUM(x) / 1000000.0 END"
        f" FROM (SELECT {case} AS x FROM json_each("
        f"CASE WHEN json_valid({alias}.usage) THEN {alias}.usage ELSE '{{}}' END) e))"
    )


def _cost_fixture_blobs() -> list[str]:
    """usage blobs covering every shape the two cost rules have to agree on.

    Derived from `PRICES` rather than hardcoded, so a new model or a new bucket
    is exercised the moment it is added.
    """
    def buckets(n: int) -> dict[str, int]:
        # distinct per-field values, so a swapped multiplier cannot cancel out
        return {f: n * (i + 1) * 1000 + i for i, f in enumerate(USAGE_FIELDS)}

    blobs: list[str] = []
    models = list(PRICES)
    for i, prefix in enumerate(models):
        blobs.append(json.dumps({prefix: buckets(i + 1)}))
        # a dated variant, the reason the rule is longest-prefix at all
        blobs.append(json.dumps({prefix + "-20260101": buckets(i + 2)}))
    # every prefix that is itself a prefix of another key: the arm order in sql
    # and the max-length scan in python must pick the same one
    for a in models:
        for b in models:
            if a != b and b.startswith(a):
                blobs.append(json.dumps({b + "-x": buckets(3)}))
    # several models in one blob — the sum, and the void when one is unpriced
    blobs.append(json.dumps({m: buckets(j + 1) for j, m in enumerate(models)}))
    blobs.append(json.dumps({models[0]: buckets(1), "some-unpriced-model": buckets(2)}))
    blobs += [
        json.dumps({"some-unpriced-model": buckets(1)}),
        json.dumps({"claude": buckets(1)}),  # shorter than any priced prefix
        json.dumps({models[0]: {}}),  # priced model, no buckets recorded
        json.dumps({models[0]: {"in": 0, "out": 0}}),  # partial buckets
        "{}",
        "",
        "   ",
        "not json at all",
        '{"unclosed": ',
        "[1, 2, 3]",  # valid json, wrong shape
        "null",
    ]
    return blobs


def _cost_disagreements(blobs) -> list[str]:
    """blobs where `usage_cost` and `_cost_sql` do not return the same figure."""
    con = sqlite3.connect(":memory:")
    con.execute("CREATE TABLE s (usage TEXT)")
    bad = []
    for blob in blobs:
        con.execute("DELETE FROM s")
        con.execute("INSERT INTO s VALUES (?)", (blob,))
        sql = con.execute(f"SELECT {_cost_sql()} FROM s").fetchone()[0]
        py = usage_cost(blob)
        if py is None or sql is None:
            same = py is None and sql is None
        else:
            same = abs(py - sql) <= 1e-9 * max(1.0, abs(py))
        if not same:
            bad.append(f"python={py!r} sql={sql!r} usage={blob[:200]!r}")
    con.close()
    return bad


def selfcheck() -> int:
    """pin `_cost_sql` to `usage_cost`; nonzero and loud when they drift apart."""
    failed = False
    fixture = _cost_fixture_blobs()
    bad = _cost_disagreements(fixture)
    if bad:
        failed = True
        print(
            f"COST MISMATCH: usage_cost and _cost_sql disagree on {len(bad)} of "
            f"{len(fixture)} fixture blobs — the sql rule in _cost_sql() no longer "
            "matches the python one in usage_cost():",
            file=sys.stderr,
        )
        for line in bad:
            print("  " + line, file=sys.stderr)
    else:
        print(f"cost: python and sql agree on {len(fixture)} fixture blobs")

    # the real cache when there is one, on top of the fixture, never instead
    if CACHE_DB.exists():
        con = open_cache()
        if con is None:
            print("cost: real cache skipped (schema mismatch)")
        else:
            rows = [r["usage"] for r in con.execute("SELECT usage FROM sessions")]
            con.close()
            bad = _cost_disagreements(rows)
            if bad:
                failed = True
                print(
                    f"COST MISMATCH: {len(bad)} of {len(rows)} cached rows disagree:",
                    file=sys.stderr,
                )
                for line in bad[:20]:
                    print("  " + line, file=sys.stderr)
            else:
                print(f"cost: python and sql agree on {len(rows)} cached rows")
    else:
        print("cost: no cache at hand, fixture only")
    return 1 if failed else 0


def _remove_db() -> None:
    """drop the cache *and its wal sidecars* — a stale wal fails the next open."""
    for suffix in ("", "-wal", "-shm"):
        Path(str(CACHE_DB) + suffix).unlink(missing_ok=True)


def _open(path: Path) -> sqlite3.Connection:
    con = sqlite3.connect(path, check_same_thread=False)
    con.row_factory = sqlite3.Row
    con.execute("PRAGMA journal_mode=WAL")
    con.execute("PRAGMA synchronous=NORMAL")
    con.execute("PRAGMA busy_timeout=15000")
    con.executescript(SCHEMA)
    return con


def connect(reset: bool = False) -> sqlite3.Connection:
    CACHE_DB.parent.mkdir(parents=True, exist_ok=True)
    if reset:
        _remove_db()
    try:
        con = _open(CACHE_DB)
        row = con.execute("SELECT v FROM meta WHERE k = 'schema'").fetchone()
        ok = row is not None and int(row["v"]) == SCHEMA_VERSION
    except sqlite3.DatabaseError:
        # the old table shape can even reject the new index statements
        con, ok = None, False
    if not ok:
        if con is not None:
            con.close()
        # an older cache layout cannot be migrated in place; rebuild it
        _remove_db()
        con = _open(CACHE_DB)
        con.execute(
            "INSERT OR REPLACE INTO meta VALUES ('schema', ?)", (str(SCHEMA_VERSION),)
        )
        con.commit()
    return con


def open_cache() -> sqlite3.Connection | None:
    """read-side open for the cli: never rebuilds, never blocks for a minute."""
    if not CACHE_DB.exists():
        print(
            f"no index at {CACHE_DB} — run `ccbrowse.py` once to build it",
            file=sys.stderr,
        )
        return None
    try:
        con = _open(CACHE_DB)
        row = con.execute("SELECT v FROM meta WHERE k = 'schema'").fetchone()
        if row is not None and int(row["v"]) == SCHEMA_VERSION:
            return con
        con.close()
    except sqlite3.DatabaseError:
        pass
    print(
        "index was built by an older schema — run `ccbrowse.py` to rebuild it",
        file=sys.stderr,
    )
    return None


def warn_if_stale(con: sqlite3.Connection) -> None:
    """say so on stderr, but still answer from whatever is cached."""
    known = {
        r["path"]: (r["mtime"], r["size"])
        for r in con.execute("SELECT path, mtime, size FROM sessions")
    }
    files = session_files()
    changed = 0
    for p in files:
        try:
            st = p.stat()
        except OSError:
            continue
        if known.get(str(p)) != (int(st.st_mtime), st.st_size):
            changed += 1
    if changed:
        print(
            f"index is stale: {changed} of {len(files)} logs changed since it was"
            " built — answering from the cache anyway",
            file=sys.stderr,
        )


def session_files() -> list[Path]:
    """every log: top-level sessions plus the subagent transcripts beneath them."""
    if not PROJECTS.is_dir():
        return []
    out: list[Path] = []
    for d in PROJECTS.iterdir():
        if not d.is_dir():
            continue
        out.extend(d.glob("*.jsonl"))
        out.extend(d.glob("*/**/*.jsonl"))
    return out


def reindex(con: sqlite3.Connection, quiet: bool = False) -> int:
    files = session_files()
    known = {
        r["path"]: (r["mtime"], r["size"], r["session_id"])
        for r in con.execute("SELECT path, mtime, size, session_id FROM sessions")
    }
    stale, live = [], set()
    for p in files:
        sp = str(p)
        live.add(sp)
        try:
            st = p.stat()
        except OSError:
            continue
        if known.get(sp, (None, None, None))[:2] != (int(st.st_mtime), st.st_size):
            stale.append(sp)

    gone = set(known) - live
    if gone:
        con.executemany("DELETE FROM sessions WHERE path = ?", [(g,) for g in gone])
        _fts_drop(con, [known[g][2] for g in gone])

    if not stale:
        con.commit()
        return 0

    if not quiet:
        print(f"indexing {len(stale)} of {len(files)} logs...", flush=True)

    # one scan clears every stale session's rows; per-session deletes would each
    # walk the whole fts table
    _fts_drop(
        con,
        [known[s][2] for s in stale if s in known]
        + [file_identity(Path(s))[1] for s in stale if s not in known],
    )

    sql = f"INSERT OR REPLACE INTO sessions VALUES ({','.join('?' * len(COLUMNS))})"
    fts_sql = "INSERT INTO msg_fts (text, session_id, role, seq) VALUES (?, ?, ?, ?)"
    done = 0
    batch: list[tuple] = []
    fts_batch: list[tuple] = []
    workers = min(os.cpu_count() or 4, 12)

    with ProcessPoolExecutor(max_workers=workers) as pool:
        for rec in pool.map(scan_file, stale, chunksize=8):
            done += 1
            if rec is None:
                continue
            docs = rec.pop("_docs")
            batch.append(tuple(rec[c] for c in COLUMNS))
            sid = rec["session_id"]
            fts_batch.extend((t, sid, role, seq) for role, seq, t in docs)
            if len(batch) >= 150:
                con.executemany(sql, batch)
                con.executemany(fts_sql, fts_batch)
                con.commit()
                batch.clear()
                fts_batch.clear()
            if not quiet and done % 250 == 0:
                print(f"  {done}/{len(stale)}", flush=True)
        if batch:
            con.executemany(sql, batch)
            con.executemany(fts_sql, fts_batch)
    con.commit()
    return len(stale)


def _fts_drop(con: sqlite3.Connection, session_ids: list[str]) -> None:
    if not session_ids:
        return
    for i in range(0, len(session_ids), 500):
        chunk = session_ids[i : i + 500]
        con.execute(
            f"DELETE FROM msg_fts WHERE session_id IN ({','.join('?' * len(chunk))})",
            chunk,
        )


_vec_state: dict = {"matrix": None, "rows": None, "model": None, "fingerprint": None}


def _fingerprint(con) -> str:
    r = con.execute(
        "SELECT COUNT(*) c, COALESCE(MAX(mtime), 0) m FROM sessions"
    ).fetchone()
    n = con.execute("SELECT COUNT(*) FROM msg_fts").fetchone()[0]
    return f"{r['c']}-{r['m']}-{n}"


def get_model():
    if _vec_state["model"] is None:
        _vec_state["model"] = StaticModel.from_pretrained(EMBED_MODEL)
    return _vec_state["model"]


def build_vectors(con, quiet: bool = False) -> int:
    """embed every indexed message; cheap enough to redo wholesale on change."""
    if not SEMANTIC_OK:
        return 0
    fp = _fingerprint(con)
    meta = con.execute("SELECT v FROM meta WHERE k = 'vec_fp'").fetchone()
    if meta and meta["v"] == fp and VEC_FILE.exists():
        return 0

    rows = con.execute(
        "SELECT rowid, text FROM msg_fts ORDER BY rowid"
    ).fetchall()
    if not rows:
        return 0
    if not quiet:
        print(f"embedding {len(rows)} messages...", flush=True)

    model = get_model()
    # the tail of a long message rarely changes its topic; cap for speed
    vecs = model.encode([r["text"][:1200] for r in rows], show_progress_bar=False)
    vecs = np.asarray(vecs, dtype=np.float32)
    norms = np.linalg.norm(vecs, axis=1, keepdims=True)
    vecs /= np.maximum(norms, 1e-9)
    # write-then-rename: a reader holding the old file mmap'd keeps reading the
    # old inode instead of seeing a half-written matrix
    # (the name must still end in .npy or numpy appends it)
    tmp = VEC_FILE.with_name("vectors.tmp.npy")
    np.save(tmp, vecs)
    os.replace(tmp, VEC_FILE)

    con.execute("DROP TABLE IF EXISTS vec_rows")
    con.execute("CREATE TABLE vec_rows (i INTEGER PRIMARY KEY, rid INTEGER)")
    con.executemany(
        "INSERT INTO vec_rows VALUES (?, ?)",
        [(i, r["rowid"]) for i, r in enumerate(rows)],
    )
    con.execute("INSERT OR REPLACE INTO meta VALUES ('vec_fp', ?)", (fp,))
    con.commit()
    _vec_state.update(matrix=None, rows=None, fingerprint=None)
    return len(rows)


def load_vectors(con):
    if not SEMANTIC_OK:  # numpy is absent; a hand-crafted mode=semantic must not 500
        return None, None
    fp = _fingerprint(con)
    if _vec_state["matrix"] is not None and _vec_state["fingerprint"] == fp:
        return _vec_state["matrix"], _vec_state["rows"]
    if not VEC_FILE.exists():
        return None, None
    matrix = np.load(VEC_FILE, mmap_mode="r")
    try:
        rows = [r["rid"] for r in con.execute("SELECT rid FROM vec_rows ORDER BY i")]
    except sqlite3.OperationalError:
        # a schema bump deletes the database — and with it vec_rows — but not
        # vectors.npy, so the file can outlive its row mapping. that is "no
        # semantic index", not a 500 for every request.
        return None, None
    if len(rows) != matrix.shape[0]:
        return None, None
    _vec_state.update(matrix=matrix, rows=rows, fingerprint=fp)
    return matrix, rows


def subagent_parents(con) -> dict[str, str]:
    """subagent row id -> the session that spawned it, for rolling hits up."""
    return {
        r["session_id"]: r["parent_id"]
        for r in con.execute(
            "SELECT session_id, parent_id FROM sessions"
            " WHERE kind = 'subagent' AND parent_id != ''"
        )
    }


def semantic_hits(con, q: str, pool: int = 600) -> dict[str, dict]:
    """query -> {session_id: {score, snippet, n_hits}} over the whole corpus.

    a hit inside a subagent transcript is reported against its parent session,
    flagged `via_subagent`, since the subagent is not a browsable row.
    """
    matrix, rows = load_vectors(con)
    if matrix is None:
        return {}
    parents = subagent_parents(con)
    qv = np.asarray(get_model().encode([q])[0], dtype=np.float32)
    qv /= max(float(np.linalg.norm(qv)), 1e-9)
    scores = matrix @ qv
    take = min(pool, scores.shape[0])
    top = np.argpartition(-scores, take - 1)[:take]
    top = top[np.argsort(-scores[top])]

    out: dict[str, dict] = {}
    for i in top:
        score = float(scores[i])
        if score < 0.15:  # below this the nearest neighbour is just noise
            break
        row = con.execute(
            "SELECT session_id, text FROM msg_fts WHERE rowid = ?", (rows[int(i)],)
        ).fetchone()
        if row is None:
            continue
        raw_sid = row["session_id"]
        sid = parents.get(raw_sid, raw_sid)
        via = 1 if raw_sid in parents else 0
        if sid in out:
            out[sid]["n_hits"] += 1
            out[sid]["via_subagent"] |= via
        else:
            text = " ".join(row["text"].split())
            out[sid] = {
                "score": score,
                "snip": text[:260] + ("…" if len(text) > 260 else ""),
                "n_hits": 1,
                "via_subagent": via,
            }
    return out


def fts_query(q: str) -> str:
    """user text -> a MATCH expression that cannot be a syntax error."""
    quoted = re.findall(r'"([^"]+)"', q)
    rest = re.sub(r'"[^"]+"', " ", q)
    terms = [f'"{p}"' for p in quoted]
    for tok in re.findall(r"[\w#@./-]+", rest, re.UNICODE):
        tok = tok.replace('"', "")
        if tok:
            terms.append(f'"{tok}"*')
    return " ".join(terms)


# subagent rows exist only to be searched; they are never listed on their own
BASE_FILTERS = ["kind = 'session'", "sidechain = 0", "(n_user + n_assistant) > 0"]

# a pasted session id, or the 8-char prefix `list`/`search` print
_SESSION_ID = re.compile(r"[0-9a-f]{8}[0-9a-f-]*", re.IGNORECASE)


def id_lookup(con, q: str, cols: str) -> list:
    """rows whose session id starts with `q`, or [] if `q` is not id-shaped.

    the project/branch facets are deliberately not applied: an id names one
    conversation, and a filter left over from browsing should not hide it. the
    regex admits only hex and dashes, so `q` can carry no LIKE wildcard.
    """
    q = q.strip()
    if not _SESSION_ID.fullmatch(q):
        return []
    return con.execute(
        f"SELECT {cols} FROM sessions s"
        f" WHERE {' AND '.join(BASE_FILTERS)} AND s.session_id LIKE ?"
        " ORDER BY s.modified DESC LIMIT 20",
        (q + "%",),
    ).fetchall()


# already qualified with the `s` alias: an expression cannot take one as a
# prefix, so `ORDER BY s.` + the value would be a syntax error for the counts
COST = _cost_sql()

SORTS = {
    "recent": "s.modified DESC",
    "oldest": "s.modified ASC",
    "longest": "(s.n_user + s.n_assistant) DESC",
    "shortest": "(s.n_user + s.n_assistant) ASC",
    # an unpriced session has no cost at all, so it belongs at the bottom of
    # either direction rather than sorting as if it were free
    "costly": f"{COST} DESC",
    "cheapest": f"{COST} IS NULL, {COST} ASC",
}


# a session has lanes when a subagent transcript names it as its parent. the
# empty-log guard matches subagents_of, so this count is what the lanes view
# will actually show; idx_parent keeps the correlated scan cheap per row
LANE_COUNT = (
    "(SELECT COUNT(*) FROM sessions a WHERE a.kind = 'subagent'"
    " AND a.parent_id = s.session_id AND (a.n_user + a.n_assistant) > 0)"
)


def _filters(
    project: str, branch: str, since: str, titled: str, lanes: str = "",
    mincost: str = "",
) -> tuple[str, list]:
    where = list(BASE_FILTERS)
    args: list = []
    if project:
        where.append("project = ?")
        args.append(project)
    if branch:
        where.append("branch = ?")
        args.append(branch)
    if since:
        where.append("modified >= ?")
        args.append(since)
    if titled == "1":
        where.append("(custom_title != '' OR ai_title != '' OR summary != '')")
    if lanes == "1":
        where.append(f"{LANE_COUNT} > 0")
    if mincost:
        try:
            floor = float(mincost)
        except ValueError:
            floor = 0.0
        if floor > 0:
            # NULL fails the comparison, which is the wanted answer: a session
            # whose cost is unknown cannot be shown to clear a threshold
            where.append(f"{COST} >= ?")
            args.append(floor)
    return " AND ".join(where), args


def _shape(d: dict) -> dict:
    """one raw result row -> what the api hands back."""
    d["tail"] = json.loads(d["tail"] or "[]")
    usage = d.pop("usage", "")
    d["tokens"] = usage_totals(usage)["total"]
    d["cost"] = usage_cost(usage)
    d["titled"] = bool(d.pop("custom_title") or d.pop("ai_title") or d.pop("summary"))
    d["via_subagent"] = 1 if d.pop("n_via", d.get("via_subagent", 0)) else 0
    d.pop("score", None)
    return d


def list_sessions(
    con, q="", project="", branch="", since="", titled="", lanes="", mincost="",
    mode="meta", sort="recent", limit=100, offset=0,
) -> dict:
    clause, args = _filters(project, branch, since, titled, lanes, mincost)
    order = SORTS.get(sort, SORTS["recent"])
    cols = (
        "s.session_id, s.project, s.branch, s.title, s.custom_title, s.ai_title,"
        " s.summary, s.first_prompt, s.created, s.modified, s.day, s.n_user,"
        " s.n_assistant, s.n_tool, s.size, s.tail, s.usage,"
        f" {LANE_COUNT} AS n_agents"
    )

    # an id is an identity, not a phrase: it resolves in every mode, and only
    # falls through to a text search when it matches no conversation
    if q:
        found = id_lookup(con, q, cols)
        if found:
            return {
                "total": len(found),
                "sessions": [_shape(dict(r)) for r in found],
                "mode": "id",
            }

    if q and mode == "semantic":
        hits = semantic_hits(con, q)
        if not hits:
            return {"total": 0, "sessions": [], "mode": mode}
        ids = list(hits)
        placeholders = ",".join("?" * len(ids))
        rows = con.execute(
            f"SELECT {cols} FROM sessions s"
            f" WHERE {clause} AND s.session_id IN ({placeholders})",
            [*args, *ids],
        ).fetchall()
        merged = []
        for r in rows:
            d = dict(r)
            d.update(hits[d["session_id"]])
            merged.append(d)
        if sort in ("relevance", "recent"):
            # relevance is the only ordering that makes sense for a fuzzy match
            merged.sort(key=lambda d: -d["score"])
        elif sort in ("longest", "shortest"):
            merged.sort(
                key=lambda d: d["n_user"] + d["n_assistant"],
                reverse=sort == "longest",
            )
        elif sort in ("costly", "cheapest"):
            def cost_key(d):
                # an unpriced session sits at the bottom of either direction,
                # the same way the sql sorts push its NULL cost down
                c = usage_cost(d["usage"])
                if c is None:
                    return (1, 0.0)
                return (0, -c if sort == "costly" else c)

            merged.sort(key=cost_key)
        else:
            merged.sort(key=lambda d: d["modified"], reverse=sort != "oldest")
        page = merged[offset : offset + limit]
        return {
            "total": len(merged),
            "sessions": [_shape(d) for d in page],
            "mode": mode,
        }

    if q and mode == "content":
        match = fts_query(q)
        if not match:
            return {"total": 0, "sessions": [], "mode": mode}
        rank = "score ASC" if sort == "relevance" else order
        # bm25()/snippet() only work in a direct scan of the fts table, so rank
        # and extract there first, then aggregate in an outer query. with MIN(),
        # sqlite takes the bare `snip` from the row that produced the minimum.
        # MATERIALIZED is required: an inlined cte loses the fts context and
        # sqlite raises "unable to use function bm25 in the requested context".
        # `owner` maps a hit's row back to a listable session: a hit inside a
        # subagent transcript counts for the session that spawned it. summing
        # `via` (rather than MAX) keeps MIN(score) the query's only min/max
        # aggregate, which is what lets the bare `snip` come from the best row.
        owner = (
            "  SELECT CASE WHEN m.kind = 'subagent' THEN m.parent_id ELSE raw.sid END"
            "    AS session_id,"
            "    CASE WHEN m.kind = 'subagent' THEN 1 ELSE 0 END AS via,"
            "    raw.score, raw.snip"
            "  FROM raw JOIN sessions m ON m.session_id = raw.sid"
        )
        sql = (
            f"WITH raw AS MATERIALIZED ("
            f"  SELECT session_id AS sid, bm25(msg_fts) AS score,"
            f"    snippet(msg_fts, 0, '\x02', '\x03', '…', 14) AS snip"
            f"  FROM msg_fts WHERE msg_fts MATCH ?),"
            f" mapped AS ({owner}),"
            f" hits AS ("
            f"  SELECT session_id, MIN(score) AS score, COUNT(*) AS n_hits,"
            f"    SUM(via) AS n_via, snip"
            f"  FROM mapped GROUP BY session_id)"
            f" SELECT {cols}, h.n_hits, h.snip, h.score, h.n_via"
            f" FROM hits h JOIN sessions s ON s.session_id = h.session_id"
            f" WHERE {clause} ORDER BY {rank} LIMIT ? OFFSET ?"
        )
        count_sql = (
            f"WITH raw AS MATERIALIZED ("
            f"  SELECT DISTINCT session_id AS sid FROM msg_fts WHERE msg_fts MATCH ?),"
            f" hits AS (SELECT DISTINCT"
            f"   CASE WHEN m.kind = 'subagent' THEN m.parent_id ELSE raw.sid END"
            f"   AS session_id FROM raw JOIN sessions m ON m.session_id = raw.sid)"
            f" SELECT COUNT(*) FROM hits h JOIN sessions s ON s.session_id = h.session_id"
            f" WHERE {clause}"
        )
        try:
            total = con.execute(count_sql, [match, *args]).fetchone()[0]
            rows = con.execute(sql, [match, *args, limit, offset]).fetchall()
        except sqlite3.OperationalError as exc:
            return {"total": 0, "sessions": [], "mode": mode, "error": str(exc)}
    else:
        if q:
            clause += (
                " AND (s.title LIKE ? OR s.first_prompt LIKE ?"
                " OR s.project LIKE ? OR s.branch LIKE ?)"
            )
            args = [*args, *([f"%{q}%"] * 4)]
        total = con.execute(
            f"SELECT COUNT(*) FROM sessions s WHERE {clause}", args
        ).fetchone()[0]
        rows = con.execute(
            f"SELECT {cols} FROM sessions s WHERE {clause}"
            f" ORDER BY {order} LIMIT ? OFFSET ?",
            [*args, limit, offset],
        ).fetchall()

    return {
        "total": total,
        "sessions": [_shape(dict(r)) for r in rows],
        "mode": mode,
    }


def facets(con, project="") -> dict:
    projects = [
        {"value": r["project"], "n": r["n"]}
        for r in con.execute(
            f"SELECT project, COUNT(*) n FROM sessions s WHERE {' AND '.join(BASE_FILTERS)}"
            " GROUP BY project ORDER BY n DESC"
        )
    ]
    bargs = []
    bclause = " AND ".join(BASE_FILTERS) + " AND branch != ''"
    if project:
        bclause += " AND project = ?"
        bargs.append(project)
    branches = [
        {"value": r["branch"], "n": r["n"]}
        for r in con.execute(
            f"SELECT branch, COUNT(*) n FROM sessions s WHERE {bclause}"
            " GROUP BY branch ORDER BY n DESC LIMIT 60",
            bargs,
        )
    ]
    tot = con.execute(
        f"SELECT COUNT(*) c, SUM(n_user + n_assistant) m, MIN(day) f"
        f" FROM sessions s WHERE {' AND '.join(BASE_FILTERS)}"
    ).fetchone()
    return {
        "projects": projects,
        "branches": branches,
        "stats": {"sessions": tot["c"], "messages": tot["m"] or 0, "since": tot["f"]},
        "semantic": SEMANTIC_OK and VEC_FILE.exists(),
    }


def timeline(con, start: str, end: str, project="", branch="") -> dict:
    """sessions overlapping [start, end) with their agents' intervals.

    feeds the day/week view: one bar per session, agent intervals as intensity
    on it. cost is the whole run's (lead + agents), merged as buckets so an
    unpriced model nulls the figure instead of shrinking it. timestamps are the
    stored iso-utc strings, so the range comparison is plain string order.
    """
    where = [*BASE_FILTERS, "s.modified >= ?", "s.created < ?", "s.created != ''"]
    args: list = [start, end]
    if project:
        where.append("s.project = ?")
        args.append(project)
    if branch:
        where.append("s.branch = ?")
        args.append(branch)
    rows = con.execute(
        "SELECT s.session_id, s.title, s.project, s.branch, s.created,"
        " s.modified, s.path, s.usage, s.n_user, s.n_assistant"
        f" FROM sessions s WHERE {' AND '.join(where)} ORDER BY s.created",
        args,
    ).fetchall()
    agents: dict[str, list] = {}
    ids = [r["session_id"] for r in rows]
    for i in range(0, len(ids), 500):
        chunk = ids[i : i + 500]
        for a in con.execute(
            "SELECT parent_id, created, modified, usage, path FROM sessions"
            " WHERE kind = 'subagent' AND (n_user + n_assistant) > 0"
            f" AND created != '' AND parent_id IN ({','.join('?' * len(chunk))})",
            chunk,
        ):
            agents.setdefault(a["parent_id"], []).append(a)
    out = []
    for r in rows:
        subs = agents.get(r["session_id"], [])
        run = usage_merge([r["usage"], *[a["usage"] for a in subs]])
        out.append({
            "id": r["session_id"],
            "title": r["title"],
            "project": r["project"],
            "created": r["created"],
            "modified": r["modified"],
            "active": is_active(r["path"]),
            "n_msgs": r["n_user"] + r["n_assistant"],
            "n_agents": len(subs),
            "tokens": usage_totals(run)["total"],
            "cost": usage_cost(run),
            "agents": [
                {"start": a["created"], "end": a["modified"],
                 "active": is_active(a["path"])}
                for a in subs
            ],
        })
    return {"sessions": out}


def timeline_days(con, start: str, end: str, project="", branch="") -> dict:
    """per-day totals for the month grid, off the indexed day column.

    agent rows carry their own usage, disjoint from the lead's, so summing
    every row's buckets per day is the true day total — merged in python so
    the null-on-unpriced rule stays with usage_cost.
    """
    where = [
        "day >= ?", "day < ?", "sidechain = 0", "(n_user + n_assistant) > 0",
    ]
    args: list = [start, end]
    if project:
        where.append("project = ?")
        args.append(project)
    if branch:
        where.append("branch = ?")
        args.append(branch)
    days: dict[str, dict] = {}
    for r in con.execute(
        f"SELECT day, kind, usage FROM sessions WHERE {' AND '.join(where)}", args
    ):
        d = days.setdefault(r["day"], {"n": 0, "usages": []})
        if r["kind"] == "session":
            d["n"] += 1
        if r["usage"]:
            d["usages"].append(r["usage"])
    out = []
    for day in sorted(days):
        run = usage_merge(days[day]["usages"])
        out.append({
            "day": day,
            "sessions": days[day]["n"],
            "tokens": usage_totals(run)["total"],
            "cost": usage_cost(run) if days[day]["usages"] else None,
        })
    return {"days": out}


def agent_tool_calls(path: Path) -> dict[str, str]:
    """agent id -> the id of the Task tool call that spawned it, where the log says.

    two places record the link: the `progress` frames streamed from a running
    subagent (`data.agentId` + `parentToolUseID`) and the final tool_result the
    parent receives (`toolUseResult.agentId`). agents that were not dispatched
    through a tool call at all — warmups, and named team agents — appear in
    neither, so they simply have no id here.
    """
    out: dict[str, str] = {}
    try:
        fh = path.open("r", encoding="utf-8", errors="replace")
    except OSError:
        return out
    with fh:
        for line in fh:
            if '"agentId"' not in line:
                continue
            try:
                d = json.loads(line)
            except json.JSONDecodeError:
                continue
            data = d.get("data")
            if d.get("type") == "progress" and isinstance(data, dict):
                aid, tid = data.get("agentId"), d.get("parentToolUseID")
                if aid and tid:
                    out.setdefault(aid, tid)
            res = d.get("toolUseResult")
            if isinstance(res, dict) and res.get("agentId"):
                msg = d.get("message")
                content = msg.get("content") if isinstance(msg, dict) else None
                if isinstance(content, list):
                    for b in content:
                        if isinstance(b, dict) and b.get("type") == "tool_result":
                            if b.get("tool_use_id"):
                                out[res["agentId"]] = b["tool_use_id"]
    return out


def subagents_of(con, session_id: str, path: str = "") -> list[dict]:
    rows = con.execute(
        "SELECT session_id, agent_id, agent_type, agent_name, model, spawn_depth,"
        " parent_agent_id, tool_use_id, title, n_user, n_assistant, created,"
        " modified, description, path, usage"
        " FROM sessions WHERE kind = 'subagent' AND parent_id = ?"
        " AND (n_user + n_assistant) > 0 ORDER BY created, session_id",
        (session_id,),
    ).fetchall()
    if not rows:
        return []
    # the sidecar states the spawning call outright; only fall back to reading
    # it out of the parent transcript for the agents whose sidecar is missing
    links = (
        agent_tool_calls(Path(path))
        if path and any(not r["tool_use_id"] for r in rows)
        else {}
    )
    return [
        {
            "id": r["session_id"],
            "agent_id": r["agent_id"],
            "agent_type": r["agent_type"],
            "agent_name": r["agent_name"],
            "model": r["model"],
            "spawn_depth": r["spawn_depth"],
            "parent_agent_id": r["parent_agent_id"],
            "title": r["title"],
            "description": r["description"],
            "n_events": r["n_user"] + r["n_assistant"],
            "started": r["created"],
            # the lane's own end. never the parent's tool_result: a
            # background-spawned Task reports back when the child *launches*.
            "ended": r["modified"],
            "active": is_active(r["path"]),
            "usage": _usage_buckets(r["usage"]),
            "tokens": usage_totals(r["usage"])["total"],
            "cost": usage_cost(r["usage"]),
            "tool_use_id": r["tool_use_id"] or links.get(r["agent_id"], ""),
        }
        for r in rows
    ]


# ---------------------------------------------------------------- live board

# claude code writes one file per running session here and rewrites it whenever
# that session's own status changes. this is undocumented internals: field names
# can move between releases, so everything below parses defensively and a status
# it does not recognise becomes `unknown` rather than a state we claim to know.
SESSIONS_DIR = Path.home() / ".claude" / "sessions"

# how much of a live transcript's tail to read for the activity line. enough to
# hold a whole turn's blocks, small enough that polling every live session every
# few seconds costs nothing.
LIVE_TAIL_BYTES = 64 * 1024

# the activity line is one clause, cut from the head
ACTIVITY_CHARS = 90

# waiting first: the board exists to show which session is stopped on you.
# `unknown` sorts below idle because it is the absence of a reading, not a state.
STATUS_ORDER = {"waiting": 0, "busy": 1, "shell": 2, "idle": 3, "unknown": 4}

_SENTENCE = re.compile(r"[.!?](?=\s|$)")


def proc_start(pid: int) -> str | None:
    """field 22 of `/proc/<pid>/stat` — when the process started, in clock ticks.

    the registry records this next to the pid, and comparing the two is the only
    thing that catches a stale file whose pid has since been reused. the comm
    field can contain spaces and parentheses, so the fields are counted from the
    last `)` rather than by splitting the whole line.
    """
    try:
        raw = Path(f"/proc/{pid}/stat").read_text()
    except OSError:
        return None
    fields = raw.rpartition(")")[2].split()
    return fields[19] if len(fields) > 19 else None


def pid_alive(pid: int, procstart: str = "") -> bool:
    """is the process that wrote this registry file still the one holding the pid?

    `/proc` settles it. off linux there is no start time to compare against, so
    signal 0 is the most that can be said and a pid reused since the file was
    written would pass — which is why the start time is preferred where it exists.
    """
    if pid <= 0:
        return False
    start = proc_start(pid)
    if start is not None:
        return not procstart or start == procstart
    if Path("/proc").is_dir():
        return False  # linux, and the process is simply gone
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except OSError:
        pass  # exists but is not ours to signal
    return True


def transcript_path(session_id: str, cwd: str = "") -> Path | None:
    """the log a live session is writing, for one the index has not seen yet.

    claude code names a project directory after the cwd with every character
    outside `[A-Za-z0-9]` replaced by a dash, so the path is derivable without a
    scan; the glob is the fallback for a session whose cwd is not what it was.
    """
    if cwd:
        p = PROJECTS / re.sub(r"[^a-zA-Z0-9]", "-", cwd) / f"{session_id}.jsonl"
        if p.exists():
            return p
    return next(PROJECTS.glob(f"*/{session_id}.jsonl"), None)


def tail_records(path: Path, limit: int = LIVE_TAIL_BYTES) -> list[dict]:
    """the last few records of a transcript, parsed, still in file order.

    a bounded read from the end rather than `scan_file`'s forward pass over the
    whole file: this runs for every live session every few seconds. the first
    line of the window is dropped because the window starts mid-line, and any
    line that fails to decode is dropped too — the file may be mid-write.
    """
    try:
        with path.open("rb") as fh:
            fh.seek(0, os.SEEK_END)
            size = fh.tell()
            fh.seek(max(0, size - limit))
            chunk = fh.read()
    except OSError:
        return []
    lines = chunk.split(b"\n")
    if size > limit and lines:
        lines.pop(0)
    out = []
    for raw in lines:
        raw = raw.strip()
        if not raw:
            continue
        try:
            d = json.loads(raw)
        except (json.JSONDecodeError, UnicodeDecodeError):
            continue
        if isinstance(d, dict):
            out.append(d)
    return out


def _content(rec: dict) -> list:
    """the content blocks of one transcript record, or an empty list."""
    msg = rec.get("message")
    content = msg.get("content") if isinstance(msg, dict) else None
    if not isinstance(content, list):
        return []
    return [b for b in content if isinstance(b, dict)]


def open_tool_calls(recs: list[dict]) -> list[dict]:
    """the `tool_use` blocks in this window that no `tool_result` answers yet.

    this is the one thing the registry can never say — it knows a session is
    busy, never what it is busy with. nothing else in the repo computes it:
    `agent_tool_calls` pairs a dispatch with the agent it spawned, a different
    edge. a result always follows its call, so a window holding the call holds
    the result too if one has come back.
    """
    answered = {
        b["tool_use_id"]
        for d in recs
        for b in _content(d)
        if b.get("type") == "tool_result" and b.get("tool_use_id")
    }
    return [
        b
        for d in recs
        if d.get("type") == "assistant"
        for b in _content(d)
        if b.get("type") == "tool_use" and b.get("id") not in answered
    ]


def _tool_hint(block: dict) -> tuple[str, str]:
    """(tool name, the input that identifies the call) for one `tool_use` block.

    `block_text` already picks the right input with the right precedence; this
    splits its one string back apart and loses its 200-char cap, which is two
    lines too long for a card.
    """
    _, text = block_text(block)
    name, _, hint = text.partition(": ")
    # a bare absolute path is the one hint whose head is the useless part: every
    # one of them opens with the same home directory. the tail names the file.
    if hint.startswith("/") and not any(c.isspace() for c in hint):
        parts = hint.rstrip("/").split("/")
        if len(parts) > 3:
            hint = ".../" + "/".join(parts[-2:])
    return name, hint


def _clause(text, cap: int = ACTIVITY_CHARS, quoted: bool = False) -> str:
    """one line of detail: whitespace collapsed, cut at a sentence end or `cap`.

    cut from the head, because the head is the part that stays legible — a
    truncated command still reads (`grep -rn "SCHEMA_VERSION" --include…`) and
    its middle does not.

    `quoted` is for text that came out of a shell command, where a cut landing
    inside a quoted string leaves a stray quote on screen. it is off for prose,
    where every apostrophe would otherwise look like an unclosed quote and throw
    away most of the line. even then the backtrack is refused when it would cost
    more than a third of the budget: a stray quote reads better than three words.
    """
    t = " ".join(str(text or "").split())
    m = _SENTENCE.search(t)
    if m and m.end() <= cap:
        return t[: m.end()]
    if len(t) <= cap:
        return t
    cut = t[:cap]
    if quoted:
        for ch in ('"', "'", "`"):
            if cut.count(ch) % 2:
                back = cut[: cut.rindex(ch)]
                if len(back) >= cap * 2 // 3:
                    cut = back
    return cut.rstrip() + "…"


# a card is a glance surface, so emphasis markers are noise rather than emphasis
_MD_MARKS = re.compile(r"\*\*|`|(?<=\s)[*_](?=\S)|(?<=\S)[*_](?=\s|$)")


def _call_by_id(recs: list[dict], tool_use_id: str) -> dict | None:
    for d in recs:
        if d.get("type") != "assistant":
            continue
        for b in _content(d):
            if b.get("type") == "tool_use" and b.get("id") == tool_use_id:
                return b
    return None


def activity_of(path: Path | None) -> dict:
    """what a live session is doing right now: `{kind, label, detail, failed}`.

    the line names the work, never the bytes — one clause with a subject, so the
    board stays readable at a glance. four cases are worded: a tool call in
    flight, a tool that just finished, assistant prose mid-turn, and a prompt
    with no reply yet. everything else (thinking, compaction, a subagent
    dispatch) falls back to a bare `working`. an empty `kind` means the
    transcript could not be read at all; an empty column is honest, a guessed
    one is not.
    """
    blank = {"kind": "", "label": "", "detail": "", "failed": False}
    if path is None:
        return blank
    recs = tail_records(path)
    if not recs:
        return blank

    # the most valuable line on the board, so it is decided before the walk back:
    # a result arriving for one of three calls must not read as "just finished"
    calls = open_tool_calls(recs)
    if calls:
        name, hint = _tool_hint(calls[0])
        label = f"{name} ×{len(calls)}" if len(calls) > 1 else name
        return {
            "kind": "tool", "label": label,
            "detail": _clause(hint, quoted=True), "failed": False,
        }

    for d in reversed(recs):
        kind = d.get("type")
        if kind not in ("user", "assistant"):
            continue
        blocks = message_blocks(d.get("message") or {})
        if not blocks:
            continue
        if kind == "user":
            res = next((b for k, _, b in blocks if k == "tool_result"), None)
            if res is not None:
                # the call, never the result body: results are enormous and
                # usually a wall of file contents. the outcome only when it is bad
                call = _call_by_id(recs, res.get("tool_use_id", ""))
                if call is None:
                    break
                name, hint = _tool_hint(call)
                return {
                    "kind": "done", "label": name,
                    "detail": _clause(hint, quoted=True),
                    "failed": bool(res.get("is_error")),
                }
            text = next((t for k, t, _ in blocks if k == "text" and t.strip()), "")
            if not text:
                continue
            # a message from another session is that session's ask, not the
            # user's — labelling it "asked" would credit the wrong sender
            inbound = inbound_message(text)
            sender, body = inbound if inbound else ("asked", text)
            ask = _clause(_MD_MARKS.sub("", clean_prompt(body)))
            if not ask:
                break  # a turn that was only wrappers says nothing worth showing
            return {"kind": "ask", "label": sender, "detail": ask, "failed": False}
        text = next(
            (t for k, t, _ in reversed(blocks) if k == "text" and t.strip()), ""
        )
        if text:
            # the one case where the model's own words are the best summary
            return {
                "kind": "prose", "label": "",
                "detail": _clause(_MD_MARKS.sub("", text)), "failed": False,
            }
        break  # thinking only, or blocks with nothing to say

    return {"kind": "working", "label": "working", "detail": "", "failed": False}


def registry_rows() -> list[dict]:
    """every parseable session file whose process is still the one that wrote it."""
    out = []
    for f in sorted(SESSIONS_DIR.glob("*.json")):
        try:
            d = json.loads(f.read_text(encoding="utf-8", errors="replace"))
        except (OSError, json.JSONDecodeError):
            continue
        if not isinstance(d, dict) or not d.get("sessionId"):
            continue
        try:
            pid = int(d.get("pid") or 0)
        except (TypeError, ValueError):
            continue
        if pid_alive(pid, str(d.get("procStart") or "")):
            out.append(d)
    return out


def live_sessions(con) -> dict:
    """one row per claude code session running on this machine, right now.

    state comes from the registry — a fact each session wrote about itself,
    which is why "blocked on you" is read here rather than inferred from a
    timestamp. substance comes from a bounded read of the transcript, and the
    title, project and token totals from the index when it has caught up.

    it deliberately does not wait on the refresh loop: a session a minute old has
    no indexed row yet and still belongs on the board, with its activity line
    standing in for the title it does not have.
    """
    regs = registry_rows()
    ids = [str(d["sessionId"]) for d in regs]
    rows: dict[str, sqlite3.Row] = {}
    subs: dict[str, list] = {}
    if ids:
        marks = ",".join("?" * len(ids))
        for r in con.execute(
            "SELECT session_id, path, title, project, branch, usage"
            f" FROM sessions WHERE kind = 'session' AND session_id IN ({marks})",
            ids,
        ):
            rows[r["session_id"]] = r
        for r in con.execute(
            "SELECT parent_id, usage FROM sessions WHERE kind = 'subagent'"
            f" AND parent_id IN ({marks})",
            ids,
        ):
            subs.setdefault(r["parent_id"], []).append(r["usage"])

    now = datetime.now(timezone.utc).timestamp()
    out = []
    for d in regs:
        sid = str(d["sessionId"])
        row = rows.get(sid)
        cwd = str(d.get("cwd") or "")
        path = Path(row["path"]) if row else transcript_path(sid, cwd)
        try:
            quiet = int(now - path.stat().st_mtime) if path else None
        except OSError:
            quiet = None
        status = str(d.get("status") or "")
        if status not in STATUS_ORDER:
            status = "unknown"
        usage = usage_merge([row["usage"], *subs.get(sid, [])]) if row else {}
        out.append({
            "session_id": sid,
            "pid": int(d["pid"]),
            "name": str(d.get("name") or ""),
            "session_kind": str(d.get("kind") or ""),
            "title": row["title"] if row else "",
            "project": row["project"] if row else cwd,
            "branch": row["branch"] if row else "",
            "indexed": row is not None,
            "status": status,
            "waiting_for": str(d.get("waitingFor") or ""),
            "quiet_for": quiet,
            "activity": activity_of(path),
            # lead plus every agent it spawned, the figure a run is judged on
            "tokens": usage_totals(usage)["total"] if row else None,
            "cost": usage_cost(usage) if row else None,
        })
    # blocked first, and within a group the one that has been quiet longest —
    # for `waiting` that is the one that has been sitting on you the longest
    out.sort(key=lambda r: (STATUS_ORDER[r["status"]], -(r["quiet_for"] or 0)))
    return {"sessions": out}


def full_session(con, session_id: str) -> dict:
    row = con.execute(
        "SELECT * FROM sessions WHERE session_id = ?", (session_id,)
    ).fetchone()
    if row is None:
        return {"error": "not found"}

    events = []
    try:
        fh = Path(row["path"]).open("r", encoding="utf-8", errors="replace")
    except OSError as exc:
        return {"error": str(exc)}
    with fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                d = json.loads(line)
            except json.JSONDecodeError:
                continue
            if d.get("type") not in ("user", "assistant"):
                continue
            msg = d.get("message")
            if not isinstance(msg, dict):
                continue
            role = d["type"]
            for kind, text, block in message_blocks(msg):
                if not text:
                    continue
                sender = ""
                if kind == "text" and role == "user":
                    inbound = inbound_message(text)
                    if inbound:
                        # delivered by another session, not typed here — its own
                        # kind so the ui never shows it as the user's own turn
                        sender, text = inbound
                        kind = "agent_message"
                    else:
                        text = clean_prompt(text)
                    if not text:
                        continue
                ev = {
                    "role": role,
                    "kind": kind,
                    "text": text[:20000],
                    "ts": d.get("timestamp", ""),
                }
                if sender:
                    ev["sender"] = sender
                if kind == "tool" and block.get("id"):
                    # lets the ui line a Task call up with its subagent transcript
                    ev["tool_use_id"] = block["id"]
                    ev["tool"] = block.get("name", "")
                events.append(ev)
    meta = {k: row[k] for k in row.keys() if k != "tail"}
    meta["usage"] = _usage_buckets(row["usage"])
    meta["tokens"] = usage_totals(row["usage"])["total"]
    meta["cost"] = usage_cost(row["usage"])
    meta["active"] = is_active(row["path"])
    stamp = con.execute("SELECT v FROM meta WHERE k = 'indexed_at'").fetchone()
    out = {"meta": meta, "events": events, "indexed_at": stamp["v"] if stamp else ""}
    if row["kind"] == "session":
        subs = subagents_of(con, session_id, row["path"])
        out["subagents"] = subs
        # the figure the run is judged on: lead plus every agent it spawned.
        # summed as buckets, not as costs, so an unpriced model nulls the whole
        # run rather than quietly dropping out of it
        run = usage_merge([row["usage"]] + [s["usage"] for s in subs])
        out["run_usage"] = run
        out["run_tokens"] = usage_totals(run)["total"]
        out["run_cost"] = usage_cost(run)
    return out


def mark_indexed(con) -> None:
    stamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    con.execute("INSERT OR REPLACE INTO meta VALUES ('indexed_at', ?)", (stamp,))
    con.commit()


def status(con) -> dict:
    n = con.execute(
        f"SELECT COUNT(*) FROM sessions s WHERE {' AND '.join(BASE_FILTERS)}"
    ).fetchone()[0]
    n_sub = con.execute(
        "SELECT COUNT(*) FROM sessions WHERE kind = 'subagent'"
    ).fetchone()[0]
    row = con.execute("SELECT v FROM meta WHERE k = 'indexed_at'").fetchone()
    return {
        "n_sessions": n,
        "n_subagents": n_sub,
        "n_messages": con.execute("SELECT COUNT(*) FROM msg_fts").fetchone()[0],
        "fingerprint": _fingerprint(con),
        "indexed_at": row["v"] if row else "",
        "semantic": SEMANTIC_OK and VEC_FILE.exists(),
    }


def refresh_loop(stop: threading.Event, interval: int, embed: bool) -> None:
    """keep the index warm while the server runs, on its own connection.

    WAL means this writer never blocks the request threads' reads, so it does
    not take Handler.lock; the request side picks up new rows on its next
    statement, and the embedding cache invalidates itself off the fingerprint.
    """
    con = connect()
    try:
        while not stop.wait(interval):
            try:
                n = reindex(con, quiet=True)
                if n:
                    if embed and SEMANTIC_OK:
                        build_vectors(con, quiet=True)
                    mark_indexed(con)
            except Exception as exc:  # a bad scan must not kill the refresher
                print(f"refresh failed: {type(exc).__name__}: {exc}", file=sys.stderr)
    finally:
        con.close()


class Handler(BaseHTTPRequestHandler):
    con: sqlite3.Connection
    lock = threading.Lock()

    def log_message(self, *_args):
        pass  # keep the terminal clean

    def _send(self, code, body: bytes, ctype="application/json"):
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body)

    def _json(self, obj, code=200):
        self._send(code, json.dumps(obj).encode(), "application/json")

    def do_GET(self):
        url = urlparse(self.path)
        qs = parse_qs(url.query)
        one = lambda k, d="": qs.get(k, [d])[0]  # noqa: E731

        try:
            if url.path == "/":
                self._send(200, UI_FILE.read_bytes(), "text/html; charset=utf-8")
            elif url.path.startswith("/ui/"):
                f = (UI_DIR / url.path[len("/ui/") :]).resolve()
                if f.is_file() and f.is_relative_to(UI_DIR.resolve()):
                    ctype = {
                        ".css": "text/css; charset=utf-8",
                        ".js": "text/javascript; charset=utf-8",
                    }.get(f.suffix, "application/octet-stream")
                    self._send(200, f.read_bytes(), ctype)
                else:
                    self._json({"error": "not found"}, 404)
            elif url.path == "/api/sessions":
                with self.lock:
                    data = list_sessions(
                        self.con,
                        q=one("q"),
                        project=one("project"),
                        branch=one("branch"),
                        since=one("since"),
                        titled=one("titled"),
                        lanes=one("lanes"),
                        mincost=one("mincost"),
                        mode=one("mode", "meta"),
                        sort=one("sort", "recent"),
                        limit=min(int(one("limit", "100")), 300),
                        offset=int(one("offset", "0")),
                    )
                self._json(data)
            elif url.path == "/api/timeline":
                fn = timeline_days if one("agg") == "day" else timeline
                with self.lock:
                    self._json(fn(
                        self.con, one("start"), one("end"),
                        one("project"), one("branch"),
                    ))
            elif url.path == "/api/facets":
                with self.lock:
                    self._json(facets(self.con, project=one("project")))
            elif url.path.startswith("/api/session/"):
                sid = unquote(url.path.rsplit("/", 1)[-1])
                with self.lock:
                    self._json(full_session(self.con, sid))
            elif url.path.startswith("/api/subagent/"):
                sid = unquote(url.path.rsplit("/", 1)[-1])
                with self.lock:
                    self._json(full_session(self.con, sid))
            elif url.path == "/api/live":
                with self.lock:
                    self._json(live_sessions(self.con))
            elif url.path == "/api/status":
                with self.lock:
                    self._json(status(self.con))
            elif url.path == "/api/refresh":
                with self.lock:
                    n = reindex(self.con, quiet=True)
                    if n:
                        mark_indexed(self.con)
                self._json({"reindexed": n})
            else:
                self._json({"error": "not found"}, 404)
        except BrokenPipeError:
            pass
        except Exception as exc:  # surface errors in the UI instead of hanging
            self._json({"error": f"{type(exc).__name__}: {exc}"}, 500)


SUBCOMMANDS = ("search", "show", "list", "selfcheck")


def fmt_tokens(n: int) -> str:
    """610k / 2.4M — one decimal above a million, none below."""
    if n >= 1_000_000:
        return f"{n / 1_000_000:.1f}M"
    if n >= 1000:
        return f"{n // 1000}k"
    return str(n)


def fmt_cost(c: float | None) -> str:
    if c is None:
        return ""
    if c < 0.01:
        return "<1c"
    return f"${c:,.2f}" if c < 100 else f"${c:,.0f}"


def _fmt_usage(tokens: int, cost: float | None) -> str:
    if not tokens:
        return ""
    bits = f"{fmt_tokens(tokens)} tok"
    return f"{bits} · {fmt_cost(cost)}" if cost is not None else bits


def _fmt_row(d: dict) -> str:
    bits = [f"{d['session_id'][:8]}  {d['modified'][:16].replace('T', ' ')}"]
    n = d["n_user"] + d["n_assistant"]
    bits.append(f"{n:>4} msg")
    if d.get("n_hits"):
        bits.append(f"{d['n_hits']:>3} hit" + ("s" if d["n_hits"] != 1 else " "))
    if d.get("via_subagent"):
        bits.append("via subagent")
    return "  ".join(bits) + f"\n    {d['title'][:110]}\n    {d['project']}"


def cli(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(prog="ccbrowse.py", description="query the index")
    sub = ap.add_subparsers(dest="cmd", required=True)

    s = sub.add_parser("search", help="search the indexed conversations")
    s.add_argument("query")
    s.add_argument("--mode", choices=("meta", "content", "semantic"), default="content")
    s.add_argument("--project", default="")
    s.add_argument("--limit", type=int, default=20)
    s.add_argument("--json", action="store_true")

    sh = sub.add_parser("show", help="print one session or subagent transcript")
    sh.add_argument("session_id")
    sh.add_argument("--json", action="store_true")

    ls = sub.add_parser("list", help="list the most recent sessions")
    ls.add_argument("--project", default="")
    ls.add_argument("--limit", type=int, default=20)
    ls.add_argument("--json", action="store_true")

    sub.add_parser("selfcheck", help="check the cost rules still agree")

    args = ap.parse_args(argv)
    if args.cmd == "selfcheck":
        # answers from the code alone, so it works on a fresh clone
        return selfcheck()

    con = open_cache()
    if con is None:
        return 1
    warn_if_stale(con)

    if args.cmd == "show":
        data = full_session(con, args.session_id)
        if args.json:
            print(json.dumps(data, indent=2))
            return 0 if "error" not in data else 1
        if "error" in data:
            print(data["error"], file=sys.stderr)
            return 1
        m = data["meta"]
        own = _fmt_usage(m.get("tokens", 0), m.get("cost"))
        print(f"{m['title']}\n{m['session_id']}  {m['project']}  {m['modified'][:16]}"
              + (f"  {own}" if own else ""))
        for sa in data.get("subagents", []):
            use = _fmt_usage(sa["tokens"], sa["cost"])
            print(f"  subagent {sa['id']}  {sa['n_events']:>4} msg  {sa['title'][:70]}"
                  + (f"  {use}" if use else ""))
        if data.get("subagents"):
            run = _fmt_usage(data.get("run_tokens", 0), data.get("run_cost"))
            if run:
                print(f"  run total (lead + {len(data['subagents'])} agents)  {run}")
        print()
        for ev in data["events"]:
            # an inbound message is nobody's turn in this session: name its sender
            label = (
                f"{ev['kind']} from {ev['sender']}"
                if ev.get("sender")
                else f"{ev['role']}/{ev['kind']}"
            )
            print(f"[{label}] {ev['text'][:2000]}\n")
        return 0

    if args.cmd == "list":
        data = list_sessions(con, project=args.project, limit=args.limit)
    else:
        if args.mode == "semantic" and not (SEMANTIC_OK and VEC_FILE.exists()):
            print(
                "semantic mode needs model2vec and a built vector index; falling"
                " back to full text",
                file=sys.stderr,
            )
            args.mode = "content"
        data = list_sessions(
            con, q=args.query, mode=args.mode, project=args.project, limit=args.limit
        )

    if args.json:
        print(json.dumps(data, indent=2))
        return 0
    if data.get("error"):
        print(data["error"], file=sys.stderr)
        return 1
    print(f"{data['total']} match(es), showing {len(data['sessions'])}\n")
    for d in data["sessions"]:
        print(_fmt_row(d) + "\n")
    return 0


def main() -> int:
    if len(sys.argv) > 1 and sys.argv[1] in SUBCOMMANDS:
        return cli(sys.argv[1:])

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--port", type=int, default=4173)
    ap.add_argument("--reindex", action="store_true", help="discard the cache first")
    ap.add_argument("--no-open", action="store_true")
    ap.add_argument("--no-embed", action="store_true", help="skip semantic indexing")
    ap.add_argument(
        "--no-refresh", action="store_true", help="do not re-index while serving"
    )
    ap.add_argument("--refresh-secs", type=int, default=REFRESH_SECS)
    args = ap.parse_args()

    con = connect(reset=args.reindex)
    reindex(con)
    if SEMANTIC_OK and not args.no_embed:
        build_vectors(con)
    elif not SEMANTIC_OK:
        print("semantic search off (no model2vec) — run with `uv run ccbrowse.py`")
    mark_indexed(con)
    total = con.execute(
        f"SELECT COUNT(*) FROM sessions s WHERE {' AND '.join(BASE_FILTERS)}"
    ).fetchone()[0]

    Handler.con = con
    server = ThreadingHTTPServer(("127.0.0.1", args.port), Handler)
    url = f"http://localhost:{args.port}"
    print(f"{total} sessions ready at {url}", flush=True)

    stop = threading.Event()
    if not args.no_refresh:
        threading.Thread(
            target=refresh_loop,
            args=(stop, max(5, args.refresh_secs), not args.no_embed),
            daemon=True,
        ).start()
    if not args.no_open:
        threading.Timer(0.4, lambda: webbrowser.open(url)).start()
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print()
    finally:
        stop.set()
    return 0


if __name__ == "__main__":
    sys.exit(main())
